### ISSUE TITLE
Introducing the JavaScript Internationalization API

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#1]
http://hacks.mozilla.org/2014/12/introducing-the-javascript-internationalization-api/

**Comment by giovicespedes** [comment]
Hola quiero contribuir con este artículo

**Comment by giovicespedes** [comment]
hola disculpen por la tardanza de la traducción olvide que tenia que hacer cuando me fui de viaje.
https://www.dropbox.com/s/oaztydotvno1qdf/newIntroducingTheJavaScript-traducido.docx?dl=0

**Comment by giovicespedes** [comment]
https://drive.google.com/file/d/0B7syRzBhCo8BU2xZWndTNnFTRWc/view?usp=sharing

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/api-de-internacionalizacion-de-javascript/

Gracias!
