### ISSUE TITLE
ES6 In Depth: Rest parameters and defaults

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#10]
https://hacks.mozilla.org/2015/05/es6-in-depth-rest-parameters-and-defaults/

**Comment by Josexv1** [comment]
Traducire este.

**Comment by Josexv1** [comment]
Hola @jvillalobos aquí esta la traducción de este tema. https://www.dropbox.com/s/ajd75xcmcaoqy4d/Parametros%20REST%20y%20default.odt?dl=0

**Comment by jvillalobos** [comment]
Parece que el archivo desapareció del Dropbox. Puede poner el borrador en el WP, igual que el otro? Gracias.

**Comment by Josexv1** [comment]
Estaba en un hiatus. Hoy mismo creo el borrador en el WP. Ademas termino las demás traducciones.

**Comment by Josexv1** [comment]
@jvillalobos Aca te deje la version en revision. El archivo lo movi a una carpeta para las traducciones de Mozilla. Por eso el link no servia. https://www.mozilla-hispano.org/?p=39396&preview=true

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/es6-en-detalle-parametros-restantes-y-por-defecto/

Gracias!
