### ISSUE TITLE
A Quantum Leap for the Web

### ISSUE THREAD

**Issue by pascalchevrel** [mozillahispano/blog-labs#102]
https://medium.com/mozilla-tech/a-quantum-leap-for-the-web-a3b7174b3c12

**Comment by SoftwareRVG** [comment]
Hola Jorge. No veo nada de animaciones.. ni de Frefox developer edition , que son mis temas preferidos...Si de momento no vas a sacar otra cosa ...Me puedes asignar este.

Saludos a todo el equipo.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/un-salto-cuantico-para-la-web/
