### ISSUE TITLE
Offline strategies come to the Service Worker Cookbook

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#103]
https://hacks.mozilla.org/2016/10/offline-strategies-come-to-the-service-worker-cookbook/

**Comment by parguello** [comment]
Me asignaré esta tarea.
Un saludo.

**Comment by parguello** [comment]
Listo para revision en WP.
Gracias!

**Comment by jvillalobos** [comment]
https://www.mozilla-hispano.org/estrategias-offline-llegan-a-guia-de-service-worker/

**Comment by jvillalobos** [comment]
Gracias!
