### ISSUE TITLE
What’s new in IndexedDB 2.0?

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#104]
https://hacks.mozilla.org/2016/10/whats-new-in-indexeddb-2-0/

**Comment by jvillalobos** [comment]
¿Cómo va el avance de esta tarea?

**Comment by AngelFQC** [comment]
Para este fin de semana lo tengo

**Comment by AngelFQC** [comment]
Siento la demora. Ahora está en pendiente de revisión

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/que-hay-de-nuevo-en-indexeddb-2-0/

Gracias!
