### ISSUE TITLE
Control mechanisms in JavaScript games

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#105]
https://hacks.mozilla.org/2016/10/control-mechanisms-in-javascript-games/

**Comment by jvillalobos** [comment]
@AngelFQC cómo va la traducción de este artículo?

**Comment by AngelFQC** [comment]
Lo estoy retomando, esta semana estará listo 😸

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/mecanismos-de-control-en-juegos-javascript/

Gracias!
