### ISSUE TITLE
WebAssembly Browser Preview

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#106]
https://hacks.mozilla.org/2016/10/webassembly-browser-preview/

**Comment by SoftwareRVG** [comment]
JORGE. ASIGNAME ESTE.  A VER SI SACAS ALGUNO DE ANIMACIONES CSS AVANZADAS PARA EL SIGUIENTE.... SALUDOS..... Rober Villar.

**Comment by jvillalobos** [comment]
¿Cómo va el avance de esta tarea?

**Comment by SoftwareRVG** [comment]
Lo siento Jorge , he tenido un grave problema familiar y no he podido ocuparme de ella. En el transcurso de esta semana , cuando ponga al día otros asuntos que tampoco he podido atender , me ocuparé de la traducción y en un par de días desde que la comienze , te la enviaré acabada.

**Comment by jvillalobos** [comment]
Está bien, no hay prisa. Nada más quiero asegurarme que no queden tareas olvidadas :)

**Comment by SoftwareRVG** [comment]
Jorge. mañana me pongo con la tarea. En uno o dos días te la envío.
Disculpa por el retraso.

**Comment by SoftwareRVG** [comment]
<div id="content-head" class="section">
  <h1 class="post__title">Vista Previa del Navegador WebAssembly</h1>
  <div class="byline">
    <h3 class="post__author">
                      <img alt='' src='https://secure.gravatar.com/avatar/2272c1032086281f75e9ab1ee43e42a4?s=64&#038;d=mm&#038;r=g' srcset='https://secure.gravatar.com/avatar/2272c1032086281f75e9ab1ee43e42a4?s=128&amp;d=mm&amp;r=g 2x' class='avatar avatar-64 photo' height='64' width='64' />        Por
                                        <a class="url" href="https://hacks.mozilla.org/author/lwagnermozilla-com/">Luke Wagner</a>                            </h2>
    <div class="post__meta">
      Publicado el
      <abbr class="published" title="2016-10-31T08:00:08-08:00">
		31 Octubre, 2016      </abbr>
      <span class="entry-cat">en
        <a href="https://hacks.mozilla.org/category/featured/" rel="category tag" title="View all posts in Featured Article" >Featured Article</a> y <a href="https://hacks.mozilla.org/category/webassembly/" rel="category tag" title="View all posts in WebAssembly" >WebAssembly</a>      </span>
            <div class="socialshare" data-type="bubbles"></div>
    </div>
  </div>
</div>

<main id="content-main" class="section article">
  <article class="post" role="article">
	<p>Desde el <a href="https://hacks.mozilla.org/2016/03/a-webassembly-milestone/">último hito de WebAssembly </a> alcanzado en Marzo, hemos trabajado duro en <a href="http://webassembly.org/">WebAssembly Community Group</a> para definir un estándar e implementar ese estándar en nuestros respectivos navegadores.</p>
<p>Estoy contento por poder decir que ahora tenemos un formato binario candidato al lanzamiento y ya hay implementaciones compatibles preparadas <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=wasm">SpiderMonkey</a> y <a href="http://v8project.blogspot.com/2016/10/webassembly-browser-preview.html">V8</a>, con trabajo en curso activo en <a href="https://blogs.windows.com/msedgedev/2016/10/31/webassembly-browser-preview/">Chakra</a> y <a href="https://bugs.webkit.org/show_bug.cgi?id=159775">JavaScriptCore</a>. Habiendo alcanzado ya este importante hito, ahora nos gustaría fomentar una información más amplia de la comunidad , especialmente a cualquier persona que haya estado esperando que las cosas se normalicen antes de echar un vistazo.</p>
<p>Durante este periodo de “vista previa del navegador”, WebAssembly seguirá estando detrás de una bandera y habrá al menos un cambio planeado para restablecer <a href="http://webassembly.org/docs/binary-encoding/#high-level-structure"> la versión binaria </a> a 1, donde esperamos que permanezca para siempre.  Por diseño , nadie debería intentar utilizar binarios WebAssembly en producción todavía. Sin embargo, suponiendo que no se encuentren problemas que requieran un tiempo considerable para solucionarlo, el grupo de la comunidad WebAssembly desearía marcar una versión inicial del estándar como "finalizada" en el primer trimestre del 2017 , lo que permitiría a los navegadores comenzar a enviar WebAssembly sin un indicador.  Por nuestra parte, en Firefox, esta luz verde significaría enviar WebAssembly en Firefox 52 (Marzo de 2017).</p>

**Comment by SoftwareRVG** [comment]
**AQUÍ OS DEJO EL ARTÍCULO TERMINADO. SALUDOS A TODA LA COMUNIDAD MOZILLA.**

**[https://docs.google.com/document/d/16YR05h6bsnnc_tjvKeKIhwCtAs0M89fszzg-mUfLJdM/edit?usp=sharing](https://docs.google.com/document/d/16YR05h6bsnnc_tjvKeKIhwCtAs0M89fszzg-mUfLJdM/edit?usp=sharing)**

-----------------------------------------------------------------------------------------------------------

<div id="content-head" class="section">
  <h1 class="post__title">Vista Previa del Navegador WebAssembly</h1>
  <div class="byline">
    <h3 class="post__author">
                      <img alt='' src='https://secure.gravatar.com/avatar/2272c1032086281f75e9ab1ee43e42a4?s=64&#038;d=mm&#038;r=g' srcset='https://secure.gravatar.com/avatar/2272c1032086281f75e9ab1ee43e42a4?s=128&amp;d=mm&amp;r=g 2x' class='avatar avatar-64 photo' height='64' width='64' />        Por
                                        <a class="url" href="https://hacks.mozilla.org/author/lwagnermozilla-com/">Luke Wagner</a>                            </h2>
    <div class="post__meta">
      Publicado el
      <abbr class="published" title="2016-10-31T08:00:08-08:00">
		31 Octubre, 2016      </abbr>
      <span class="entry-cat">en
        <a href="https://hacks.mozilla.org/category/featured/" rel="category tag" title="View all posts in Featured Article" >Featured Article</a> y <a href="https://hacks.mozilla.org/category/webassembly/" rel="category tag" title="View all posts in WebAssembly" >WebAssembly</a>      </span>
            <div class="socialshare" data-type="bubbles"></div>
    </div>
  </div>
</div>

<main id="content-main" class="section article">
  <article class="post" role="article">
	<p>Desde el <a href="https://hacks.mozilla.org/2016/03/a-webassembly-milestone/">último hito de WebAssembly </a> alcanzado en Marzo, hemos trabajado duro en <a href="http://webassembly.org/">WebAssembly Community Group</a> para definir un estándar e implementar ese estándar en nuestros respectivos navegadores.</p>
<p>Estoy contento por poder decir que ahora tenemos un formato binario candidato al lanzamiento y ya hay implementaciones compatibles preparadas <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=wasm">SpiderMonkey</a> y <a href="http://v8project.blogspot.com/2016/10/webassembly-browser-preview.html">V8</a>, con trabajo en curso activo en <a href="https://blogs.windows.com/msedgedev/2016/10/31/webassembly-browser-preview/">Chakra</a> y <a href="https://bugs.webkit.org/show_bug.cgi?id=159775">JavaScriptCore</a>. Habiendo alcanzado ya este importante hito, ahora nos gustaría fomentar una información más amplia de la comunidad , especialmente a cualquier persona que haya estado esperando que las cosas se normalicen antes de echar un vistazo.</p>
<p>Durante este periodo de “vista previa del navegador”, WebAssembly seguirá estando detrás de un indicador y habrá al menos un cambio planeado para restablecer <a href="http://webassembly.org/docs/binary-encoding/#high-level-structure"> la versión binaria </a> a 1, donde esperamos que permanezca para siempre.  Por diseño , nadie debería intentar utilizar binarios WebAssembly en producción todavía. Sin embargo, suponiendo que no se encuentren problemas que requieran un tiempo considerable para solucionarlo, el grupo de la comunidad WebAssembly desearía marcar una versión inicial del estándar como "finalizada" en el primer trimestre del 2017 , lo que permitiría a los navegadores comenzar a enviar WebAssembly sin un indicador.  Por nuestra parte, en Firefox, esta luz verde significaría enviar WebAssembly en Firefox 52 (Marzo de 2017).</p>
<h2>¿Que hay de nuevo desde el último hito?</h2>
<p>Si ha estado siguiendo el desarrollo, ha habido un gran progreso desde el último hito en marzo:</p>
<ul>
<li>Cientos de problemas presentados y resueltos en el <a href="http://github.com/webassembly/design">diseño </a> WebAssembly y <a href="http://github.com/webassembly/spec/">especificaciones</a> de repositorios.</li>
<li>Tres iteraciones sincronizadas del formato binario entre el navegador y el toolchain.</li>
<li>Una mayor expansión  de la <a href="http://webassembly.org/docs/js">JS WebAssembly API</a>,  que ahora permite a los desarrolladores solicitar explícitamente <a href="https://github.com/WebAssembly/design/blob/master/JS.md#webassemblycompile"> la compilación paralela </a>, <a href="https://github.com/WebAssembly/design/blob/master/JS.md#structured-clone-of-a-webassemblymodule">caché código-máquina y código compartido </a>, <a href="https://github.com/WebAssembly/design/blob/master/DynamicLinking.md"> vinculación dinámica</a> ( y finalmente <a href="https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#streaming-compilation"> la compilación en streaming</a>).</li>
<li>En Mozilla, una implementación completa (modulo boogs<sup><a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1313176">1</a>,<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1313180">2</a></sup>) de WebAssembly en Firefox, incluyendo la extensión del backend del compilador JIT para soportar i64 en 32-bit y el conjunto completo de <a href="https://github.com/WebAssembly/design/blob/master/Semantics.md#datatype-conversions-truncations-reinterpretations-promotions-and-demotions">operadores de de conversión de punto flotante IEEE 754</a>.</li>
<li>Progreso y optimización de la fuente de información del compilador de WebAssembly incluyendo la subida<a href="https://github.com/llvm-mirror/llvm/blob/master/lib/Target/WebAssembly/README.txt"> LLVM </a> <a href="https://github.com/kripken/emscripten/wiki/New-WebAssembly-Backend"> backend </a> y <a href="https://github.com/WebAssembly/binaryen#binaryen"> Binaryen</a>.</li>
</ul>
<p>Con todo este trabajo, también podemos obtener algunos números iniciales en las clásicas <a href="https://github.com/kripken/emscripten/blob/caa37c2e281d30195bee01207ac6c1aa61b6f831/tests/test_benchmark.py"> mediciones Emscripten- internal</a> comparando de extremo a extremo asm.js con WebAssembly [medido en 64-bit Firefox 52 (Nightly), Intel Core i7-2600 @ 3.40GHz, Linux]:</p>
<p><img src="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2016/10/asmjs-wasm-comparison.png" alt="asmjs-wasm-comparison" width="482" height="313" class="alignnone size-full wp-image-30283" srcset="https://hacks.mozilla.org/files/2016/10/asmjs-wasm-comparison.png 482w, https://hacks.mozilla.org/files/2016/10/asmjs-wasm-comparison-250x162.png 250w" sizes="(max-width: 482px) 100vw, 482px" /></p>
<p>Las aceleraciones que vemos aquí se deben a una combinación de optimizaciones de  <a href="https://github.com/WebAssembly/binaryen#binaryen">Binaryen</a>, optimizaciones de navegador y nuevas capacidades de hardware expuestas por WebAssembly. La optimización de toda la fuente de información está todavía en curso, por lo que se espera mejorar el resultado antes del lanzamiento (<strike>con anomalías, como la ligera desaceleración en Bullet, entendida y fijada</strike> <em>ACTUALIZACIÓN 11/21: <a href="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2016/11/asmjs-wasm-comparison-updated.png">fijada</a> por las optimizaciones Binaryen más recientes</em>).  Pero incluso ahora, podemos ver que WebAssembly es una mejora notable, incluso para los usuarios de Firefox que ya se han beneficiado de <a href="https://blog.mozilla.org/luke/2015/02/18/microsoft-announces-asm-js-optimizations/#asmjs-opts"> optimizaciones asm.js </a>.</p>
<p>Además, los núcleos computacionales que hacen hincapié en nuevas operaciones de WebAssembly pueden mostrar velocidades mucho mayores. Por ejemplo, utilizando el mismo sistema experimental que el anterior, un <a href="https://github.com/kripken/emscripten/blob/caa37c2e281d30195bee01207ac6c1aa61b6f831/tests/test_benchmark.py#L500"> Núcleo aritmético entero de 64 bits </a> ejecutándose un 8.93× más lento que la velocidad nativa en asm.js debido a la emulación utilizando JS operativo en 32-bit , mietras se ejecuta solo a 1.13× más lento que la velocidad nativa en WebAssembly.</p>
<h2>Probando</h2>
<p>Para probar WebAssembly, dirijasé a <a href="http://webassembly.org">webassembly.org</a> que contiene instrucciones para <a href="http://webassembly.org/getting-started/developers-guide/">compilar un módulo WebAssembly con Emscripten</a> y después <a href="http://webassembly.org/getting-started/js-api/">cargar y ejecutar un módulo WebAssembly desde JavaScript</a>.</p>
<p>Dado que esto tiene cosas todavía bastante delicadas, se apliican algunas advertencias:</p>
<p>En primer lugar, para reiterar lo anterior: Las cosas van a cambiar hasta que el estándar esté marcado y WebAssembly esté habilitado en los navegadores (¡ Y entonces esto no volverá a <em>romper la web</em> como de costumbre!).  Para ayudar a comunicar los cambios a la comunidad, publicaremos los cambios realizados o planificados en la página  <a href="http://webassembly.org/roadmap/">roadmap</a>.  También es una buena idea probar siempre con compilaciones  <a href="http://nightly.mozilla.org/">Nightly</a>.</p>
<p>En segundo lugar, la "especificación" completa de WebAssembly  está actualmente dispersa en varios archivos Markdown  del repositorio <a href="https://github.com/webassembly/design">diseño</a> , y algunos detalles (como las reglas de validación) están unicamente presentes en el <a href="https://github.com/WebAssembly/spec/tree/master/interpreter">intérprete de referencia</a>.  Durante la vista previa del navegador, recogeremos estos bits dispersos y escribiremos una especificación sencilla y coherente, en el repositorio de <a href="https://github.com/WebAssembly/spec/"> especificaciones</a>.</p>
<p>Finalmente, aunque actualmente se puede ver el formato de texto WebAssembly reproducido en modo depurado en Firefox’s , el depurado completo todavía no funciona (aunque estamos  ¡<a href="https://www.youtube.com/watch?v=R1WtBkMeGds">  Muy cerca</a> !). Sin embargo ,  mientras tanto, los experimentadores necesitarán utilizar la tradicional aplicación  de  depuración-<code>printf</code>.</p>
<p>Teniendo en cuenta estas advertencias, ya estamos viendo una gran cantidad de emocionante experimentación y esperamos ver más en los próximos meses .  Hay unos cuantos lugares que proporcionan información dependiendo  si los comentarios pertenecen al diseño general, el intérprete de referencia, o una implementación específica en el navegador; Hemos recopilado <a href="http://webassembly.org/community/feedback/">una lista de enlaces de información</a> en webassembly.org.  ¡Feliz hacking!</p>    <section class="about">
								<h2 class="about__header">Acerca de 
                          <a class="url" href="https://hacks.mozilla.org/author/lwagnermozilla-com/">
                Luke Wagner              </a>
                      </h3>
                      <p>Luke Wagner es un ingeniero de software en Mozilla  y desarrolla JavaScript y WebAssembly en Firefox.</p>
								<p><a class="url" href="https://hacks.mozilla.org/author/lwagnermozilla-com/">Más artículos de Luke Wagner&hellip;</a></p>
                  </section>
  </article>

--------------------------------------------------------------------------------------------------------
![fireshot screen capture 001 - webassembly browser preview mozilla hacks the web developer blog - _c__users_robervillargarcia_desktop_mozilla_us](https://cloud.githubusercontent.com/assets/15747545/22358861/e0a7df88-e442-11e6-97af-8b1e6c9e7ab3.png)

**Comment by jvillalobos** [comment]
Publicado:
https://www.mozilla-hispano.org/vista-preliminar-de-webassembly-en-el-navegador/

Gracias!
