### ISSUE TITLE
Crear videojuegos en Javascript

### ISSUE THREAD

**Issue by Skatox** [mozillahispano/blog-labs#109]
Me parece que se debe hacer una nota sobre esta documentación en español, me pareció genial https://mozdevs.github.io/js-for-gamedev/es/

¿Alguien se anima?

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/introduccion-al-desarrollo-de-videojuegos-en-javascript/

Gracias!
