### ISSUE TITLE
ES6 In Depth: Destructuring

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#11]
https://hacks.mozilla.org/2015/05/es6-in-depth-destructuring/

**Comment by siclemx** [comment]
Hola Jorge tomare este para traducirlo.

**Comment by jvillalobos** [comment]
¿Cómo vamos con este artículo?

**Comment by siclemx** [comment]
Mañana pongo el enlace Jorge

**Comment by jvillalobos** [comment]
Hola BoSicle, hubo progreso con esta traducción?

**Comment by jvillalobos** [comment]
Voy a tomar esta traducción, dado que no ha tenido actividad por bastante tiempo, y para mantener la secuencia de los artículos.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/es6-en-detalle-desestructuracion/
