### ISSUE TITLE
Mozilla Push Server now supports topics

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#111]
https://hacks.mozilla.org/2016/11/mozilla-push-server-now-supports-topics/

**Comment by AngelFQC** [comment]
Puesto en revisió :smile_cat:

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/el-servidor-push-de-mozilla-soporta-temas/

Gracias!
