### ISSUE TITLE
Rust and the Future of Systems Programming

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#112]
https://hacks.mozilla.org/2016/11/rust-and-the-future-of-systems-programming/

**Comment by carloschocobar** [comment]
Hola Jorge, me gustaría traducir este artículo.

**Comment by carloschocobar** [comment]
Listo para revisión. https://docs.google.com/document/d/12emkaPhiyXPXwbXRA8AmlXxepAdswY-nzWObVhU2Yv4/edit?usp=sharing

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/rust-y-el-futuro-de-la-programacion-de-sistemas/

Gracias!
