### ISSUE TITLE
Visualize animations easing in DevTools

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#113]
https://hacks.mozilla.org/2016/11/visualize-animations-easing-in-devtools/

**Comment by SoftwareRVG** [comment]
Jorge. ¿ Puedes asignarme este ? Ya sabes que me van las animaciones 3D

**Comment by SoftwareRVG** [comment]
Hola Jorge , Te envío la traducción de la última tarea que me asignaste. Lo paso a Revisión y dejo un enlace en el Waffle por si tienes mucho trabajo con el desarrollo de complementos y no pudieras encargarte personalmente .
He visto un artículo que has publicado sobre WebGl y VR. Voy a pedirte que me lo asignes , pues ya sabes que las animaciones es mi tema preferido. 

### Gracias Jorge. Saludos a todo el equipo. 
-----------------------------------------------------------------------------------------------------------
### Enlace de edición en Google-Docs :  [https://docs.google.com/document/d/1DlZhI2T4W9TmVBAbL-cYLC14p0f2dTmLzYJDgRSd_T8/edit?usp=sharing](https://docs.google.com/document/d/1DlZhI2T4W9TmVBAbL-cYLC14p0f2dTmLzYJDgRSd_T8/edit?usp=sharing)
-----------------------------------------------------------------------------------------------------------

<div id="content-head" class="section">
  <h1 class="post__title">Visualización de la Facilitación de Animaciones en DevTools </h1>
  <div class="byline">
    <h3 class="post__author">
                      <img alt='' src='https://secure.gravatar.com/avatar/84ab9576d6f4960d9d05867b5e53111e?s=64&#038;d=mm&#038;r=g' srcset='https://secure.gravatar.com/avatar/84ab9576d6f4960d9d05867b5e53111e?s=128&amp;d=mm&amp;r=g 2x' class='avatar avatar-64 photo' height='64' width='64' />        Por
                                        <a class="url" href="http://patrickbrosset.com" rel="external me">Patrick Brosset</a>                            </h2>
    <div class="post__meta">
      Publicado el
      <abbr class="published" title="2016-11-28T07:55:38-08:00">
		28 de Noiembre, 2016      </abbr>
      <span class="entry-cat">en
        <a href="https://hacks.mozilla.org/category/javascript/animations/" rel="category tag" title="View all posts in Animations" >Animations</a>, <a href="https://hacks.mozilla.org/category/css/" rel="category tag" title="View all posts in CSS" >CSS</a>, <a href="https://hacks.mozilla.org/category/demo/" rel="category tag" title="View all posts in Demo" >Demo</a>, <a href="https://hacks.mozilla.org/category/developer-tools/" rel="category tag" title="View all posts in Developer Tools" >Developer Tools</a>,  y <a href="https://hacks.mozilla.org/category/featured/" rel="category tag" title="View all posts in Featured Article" >Featured Article</a>      </span>
            <div class="socialshare" data-type="bubbles"></div>
    </div>
  </div>
</div>

<main id="content-main" class="section article">
  <article class="post" role="article">
	<p>La facilitación (o función de tiempo) de una animación  es la que dicta la forma en que progresa a través del tiempo.</p>
<p>Por ejemplo, una facilitación lineal implica que la animación se ejecuta a la misma velocidad durante toda su duración. Esto significa que si un elemento no se mueve al principio y después comienza a moverse, lo hará instantaneamente, como si ni siquiera tuviera que acelerar. A menudo, los desarrolladores web escogen otras facilitaciones que parecen más naturales , más reales. Hay unas pocas incorporaciones como <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function#single-timing-function"><code>ease, ease-in, ease-out</code> , y  <code>ease-in-out</code></a>  , e incluso es posible crear la tuya propia utilizando la función<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/single-transition-timing-function#The_cubic-bezier()_class_of_timing-functions"><code> cubic-bezier()</code> </a>.</p>
<p>Vale la pena señalar que <a href="https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector">el inspector del panel</a> en Firefox , ya te permite <a href="https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Work_with_animations#Edit_timing_functions">editar la facilitación de las animaciones en la vista de reglas del CSS</a>.</p>
<p>A partir de Firefox 52 <a href="https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Work_with_animations#Animation_inspector">el inspector del panel de animaciones</a> ahora muestra la facilitación de las animaciones directamente dentro de su linea de tiempo:</p>
<p><img class="alignnone size-large wp-image-30322" src="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2016/11/timeline-easing-500x151.png" alt="timeline-easing" width="500" height="151" srcset="https://hacks.mozilla.org/files/2016/11/timeline-easing-500x151.png 500w, https://hacks.mozilla.org/files/2016/11/timeline-easing-250x76.png 250w, https://hacks.mozilla.org/files/2016/11/timeline-easing-768x232.png 768w, https://hacks.mozilla.org/files/2016/11/timeline-easing.png 1548w" sizes="(max-width: 500px) 100vw, 500px" /></p>
<p>Esto es muy útil para obtener más información de las animaciones de un simple vistazo.</p>
<p>También hay una útil información sobre herramientas que aparece cuando se cierne sobre las animaciones. Contiene toda la información sobre el tiempo que podrías necesitar para una animación dada: incluidas su facilitación, y también su duración, iteraciones, retrasos, dirección, etc.</p>
<p><img class="alignnone size-full wp-image-30323" src="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2016/11/timing-tooltip.png" alt="timing-tooltip" width="311" height="288" srcset="https://hacks.mozilla.org/files/2016/11/timing-tooltip.png 311w, https://hacks.mozilla.org/files/2016/11/timing-tooltip-250x232.png 250w" sizes="(max-width: 311px) 100vw, 311px" /></p>
<p>A continuación se presentan varios ejemplos de como se representa la facilitación en la linea de tiempo:</p>
<ul>
<li>Una animación que se repite 3 veces, con una facilitación <code>ease-in-out</code>:<br />
<img class="alignnone size-large wp-image-30324" src="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2016/11/ease-in-out-3-iterations-500x56.png" alt="ease-in-out-3-iterations" width="500" height="56" srcset="https://hacks.mozilla.org/files/2016/11/ease-in-out-3-iterations-500x56.png 500w, https://hacks.mozilla.org/files/2016/11/ease-in-out-3-iterations-250x28.png 250w, https://hacks.mozilla.org/files/2016/11/ease-in-out-3-iterations-768x86.png 768w, https://hacks.mozilla.org/files/2016/11/ease-in-out-3-iterations.png 942w" sizes="(max-width: 500px) 100vw, 500px" /></li>
<li>Una animación infinita , con facilitación lineal:<br />
<img class="alignnone size-large wp-image-30325" src="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2016/11/linear-infinite-500x23.png" alt="linear-infinite" width="500" height="23" srcset="https://hacks.mozilla.org/files/2016/11/linear-infinite-500x23.png 500w, https://hacks.mozilla.org/files/2016/11/linear-infinite-250x11.png 250w, https://hacks.mozilla.org/files/2016/11/linear-infinite-768x35.png 768w, https://hacks.mozilla.org/files/2016/11/linear-infinite.png 1058w" sizes="(max-width: 500px) 100vw, 500px" /></li>
<li>Una animación que se repite 5 veces con una dirección alternativa, facilitación y avance de relleno <code>ease</code>:<br />
<img class="alignnone size-large wp-image-30326" src="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2016/11/ease-alternate-500x26.png" alt="ease-alternate" width="500" height="26" srcset="https://hacks.mozilla.org/files/2016/11/ease-alternate-500x26.png 500w, https://hacks.mozilla.org/files/2016/11/ease-alternate-250x13.png 250w, https://hacks.mozilla.org/files/2016/11/ease-alternate-768x39.png 768w, https://hacks.mozilla.org/files/2016/11/ease-alternate.png 1050w" sizes="(max-width: 500px) 100vw, 500px" /></li>
</ul>
<p>Y aquí hay un video que muestra varios tipos de facilitación en el inspector del panel de la animación:</p>
<p><iframe width="500" height="375" src="https://www.youtube.com/embed/zPqdS03xqQ0?feature=oembed" frameborder="0" allowfullscreen></iframe></p>
<h2>Acerca de los retrasos</h2>
<p>Hay dos tipos de retrasos que puedes utilizar en las animaciones: <code>delay</code> y <code>end-delay</code>.</p>
<p>Este último sólo puede ser utilizado con animaciones creadas con la <a href="https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API"> Web Animations API</a>. <code>end-delay</code> es útil para sincronizar varias animaciones, por ejemplo , cuando deseas que una animación comienze exactamente 1 segundo después de que haya finalizado la primera.</p>
<p>Tanto delay como end-delay pueden tener un valor positivo o negativo.</p>
<p>El inspector de la animación ahora también representa esos retrasos visualmente. Aquí hay unos pocos ejemplos:</p>
<ul>
<li>Retraso positivo:<br />
  <img src="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2016/11/positive-delay-500x58.png" alt="positive-delay" width="500" height="58" class="alignnone size-large wp-image-30327" srcset="https://hacks.mozilla.org/files/2016/11/positive-delay-500x58.png 500w, https://hacks.mozilla.org/files/2016/11/positive-delay-250x29.png 250w, https://hacks.mozilla.org/files/2016/11/positive-delay-768x89.png 768w, https://hacks.mozilla.org/files/2016/11/positive-delay.png 866w" sizes="(max-width: 500px) 100vw, 500px" />
  </li>
<li>Retraso-final positivo:<br />
  <img src="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2016/11/positive-end-delay-500x49.png" alt="positive-end-delay" width="500" height="49" class="alignnone size-large wp-image-30328" srcset="https://hacks.mozilla.org/files/2016/11/positive-end-delay-500x49.png 500w, https://hacks.mozilla.org/files/2016/11/positive-end-delay-250x24.png 250w, https://hacks.mozilla.org/files/2016/11/positive-end-delay-768x75.png 768w, https://hacks.mozilla.org/files/2016/11/positive-end-delay.png 1166w" sizes="(max-width: 500px) 100vw, 500px" />
  </li>
<li>Retraso negativo:<br />
  <img src="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2016/11/negative-delay-500x73.png" alt="negative-delay" width="500" height="73" class="alignnone size-large wp-image-30329" srcset="https://hacks.mozilla.org/files/2016/11/negative-delay-500x73.png 500w, https://hacks.mozilla.org/files/2016/11/negative-delay-250x37.png 250w, https://hacks.mozilla.org/files/2016/11/negative-delay.png 710w" sizes="(max-width: 500px) 100vw, 500px" />
  </li>
<li>Retraso final negativo:<br />
  <img src="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2016/11/negative-end-delay-500x94.png" alt="negative-end-delay" width="500" height="94" class="alignnone size-large wp-image-30330" srcset="https://hacks.mozilla.org/files/2016/11/negative-end-delay-500x94.png 500w, https://hacks.mozilla.org/files/2016/11/negative-end-delay-250x47.png 250w, https://hacks.mozilla.org/files/2016/11/negative-end-delay.png 594w" sizes="(max-width: 500px) 100vw, 500px" />
  </li>
</ul>
<h2>Efecto facilitación contra . facilitación  de keyframe</h2>
<p>Hay dos modos de aplicar la facilitación a una animación: Ya sea a través de la iteración completa de una animación, afectando a todas las propiedades por igual (efecto facilitación), o entre  <a href="https://en.wikipedia.org/wiki/Key_frame">keyframes</a> , unicamente afectando a las propiedades especificadas en esos keyframes (facilitación de keyframe ).</p>
<p>Las animaciones CSS unicamente permiten la facilitación de keyframe y esto cofunde a mucha gente. Casi todo el mundo asume que la función  <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function"><code>animation-timing-function</code></a> produce el efecto facilitación pero haciendo en su lugar la facilitación del keyframe . Sin embargo, las animaciones creadas utilizando la <a href="https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API"> Web Animations API</a> pueden utilizar ambos tipos de facilitación.</p>
<p>En este momento, el inspector de la animación solo muestra el efecto de facilitación. Esto implica que incluso si defines una animación CSS con la función no-lineal <code>animation-timing-function</code>, la linea de tiempo mostrrá una progresión lineal.</p>
<p>El <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1309468">Bug 1309468</a> abordará esto  y hará  también la facilitación del keyframe visible en el inspector de la animación. Serán bienvenidos sus pensamientos y comentarios constructivos en esta sección de comentarios, o enviando un tweet a <a href="http://twitter.com/firefoxdevtools">@FirefoxDevTools</a>.</p>    <section class="about">
								<h2 class="about__header">Acerca de 
                          <a class="url" href="http://patrickbrosset.com" rel="external me">
                Patrick Brosset              </a>
                      </h3>
                      <p>Patrick dirige el equipo de ingenieros en DevTools (herramientas para desarrolladores) de Mozilla</p>
					<ul class="author-meta fa-ul"><li><i class="fa-li fa fa-globe"></i><a href="http://patrickbrosset.com" class="website" rel="me">patrickbrosset.com</a></li><li><i class="fa-li fa fa-twitter"></i><a href="http://twitter.com/patrickbrosset" class="twitter" rel="me">@patrickbrosset</a></li></ul>            <p><a class="url" href="https://hacks.mozilla.org/author/pbrossetmozilla-com/">Más artículos de Patrick Brosset&hellip;</a></p>
                  </section>
  </article>
  

<section class="discussion">
  <hr class="dino">
  
----------------------------------------------------------------------------------------------------------
### CAPTURA DE PANTALLA ARTÍCULO TERMINADO
----------------------------------------------------------------------------------------------------------
![visualize animations easing in devtools mozilla hacks the web developer blog](https://cloud.githubusercontent.com/assets/15747545/23106048/11b7259a-f6e8-11e6-8b06-8423cd55a0bb.png)

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/visualizacion-de-la-facilitacion-de-animaciones/

Gracias!
