### ISSUE TITLE
CSS Grid and Grid Highlighter Now in Firefox Developer Edition

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#114]
https://hacks.mozilla.org/2016/12/css-grid-and-grid-highlighter-now-in-firefox-developer-edition/

**Comment by parguello** [comment]
Hola Jorge!
Me gustaría continuar con este artículo.
Un saludo.

**Comment by parguello** [comment]
Marcado para revisión en WP.
Saludos.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/grid-css-y-marcador-de-grid-ahora-en-firefox-developer-edition/

Gracias!
