### ISSUE TITLE
Async/Await Arrive in Firefox

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#115]
https://hacks.mozilla.org/2016/12/asyncawait-arrive-in-firefox/

**Comment by parguello** [comment]
Continuaré con este artículo.

**Comment by parguello** [comment]
Listo para revisión en WP.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/async-await-llega-a-firefox/

Gracias!
