### ISSUE TITLE
Firefox Hardware Report for Web Developers

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#116]
https://hacks.mozilla.org/2016/12/firefox-hardware-report/

**Comment by xexio** [comment]
Me la quedo.

**Comment by jvillalobos** [comment]
¿Cómo va el avance de esta tarea?

**Comment by jvillalobos** [comment]
Listo: https://www.mozilla-hispano.org/reporte-de-hardware-desarrolladores-web/
