### ISSUE TITLE
WebGL 2 lands in Firefox

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#119]
https://hacks.mozilla.org/2017/01/webgl-2-lands-in-firefox/

**Comment by SoftwareRVG** [comment]
Hola Jorge . ¿ Puedes asignarme este artículo ?

**Comment by SoftwareRVG** [comment]
<div id="content-head" class="section">
  <h1 class="post__title">Territorio WebGL 2 en Firefox</h1>
  <div class="byline">
    <h3 class="post__author">
                      <img alt='' src='https://secure.gravatar.com/avatar/79da6f98785139726c7c9a5f8abba32f?s=64&#038;d=mm&#038;r=g' srcset='https://secure.gravatar.com/avatar/79da6f98785139726c7c9a5f8abba32f?s=128&amp;d=mm&amp;r=g 2x' class='avatar avatar-64 photo' height='64' width='64' />        Por
                                        <a class="url" href="http://www.belenalbeza.com" rel="external me">Belén Albeza</a>,                                                  <a class="url" href="https://hacks.mozilla.org/author/jgilbertmozilla-com/">Jeff Gilbert</a>                            </h2>
    <div class="post__meta">
      Publicado el
      <abbr class="published" title="2017-01-24T08:03:59-07:00">
         24 de Enero, 2017      </abbr>
      <span class="entry-cat">en
        <a href="https://hacks.mozilla.org/category/featured/" rel="category tag" title="View all posts in Featured Article" >Featured Article</a>, <a href="https://hacks.mozilla.org/category/firefox/" rel="category tag" title="View all posts in Firefox" >Firefox</a>, <a href="https://hacks.mozilla.org/category/firefox/firefox-releases/" rel="category tag" title="View all posts in Firefox Releases" >Firefox Releases</a>, <a href="https://hacks.mozilla.org/category/games/" rel="category tag" title="View all posts in Games" >Games</a>, <a href="https://hacks.mozilla.org/category/webapi/" rel="category tag" title="View all posts in Web APIs" >Web APIs</a>,  y <a href="https://hacks.mozilla.org/category/webgl/" rel="category tag" title="View all posts in WebGL" >WebGL</a>      </span>
            <div class="socialshare" data-type="bubbles"></div>
    </div>
  </div>
</div>

<main id="content-main" class="section article">
  <article class="post" role="article">
	<p>Con el lanzamiento de Firefox 51, <b>¡ Ha llegado el soporte de WebGL 2 !</b> WebGL es una API estándar para representar gráficos 3D en la web. Está basado en OpenGL ES, que se utiliza comunmente para los juegos móviles.</p>
<p>Hasta la fecha, hemos sido capaces de utilizar WebGL 1 (basado en OpenGL ES 2) para representar gráficos fantásticos en un elemento &lt;canvas&gt; . WebGL 2, sin embargo, está <b>basado en la especificación </b><a href="https://www.khronos.org/registry/gles/specs/3.0/es_spec_3.0.pdf"><b>OpenGL ES 3.0</b></a> , que introduce nuevas características – la mayoría de ellas destinadas a aumentar el rendimiento y la fidelidad visual .</p>
<p>Hasta hoy, WebGL 2 ha sido utilizable detras de una bandera , o en Developer Edition o Nightly, pero con Firefox 51, está ahora desbloqueado para todos los usuarios de Firefox en Windows, MacOS, y Linux.</p>
<h2>Demostración: &ldquo;Después de la inundación&rdquo; (PlayCanvas)</h2>


<p>Para darte una idea del contenido que permite WebGL 2 , estamos emocionados por destacar <a href="https://playcanv.as/e/p/44MRmJRU/"><b>Después de la inundación</b></a>, una demostración WebGL 2 interactiva de <b>PlayCanvas</b>. (Tenga en cuenta que esta demostración está actualmente disponible solamente en versión escritorio , con soporte móvil en breve.) De un paseo a través del fantástico entorno de agua , vidrio, y acero , ¡Desarrollándolo completamente dentro de su navegador!</p>
<p class="thumb-grid"><a href="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2017/01/atf-0.jpg"><img src="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2017/01/atf-0.jpg" alt="atf-0"/></a><a href="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2017/01/atf-1.jpg"><img src="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2017/01/atf-1.jpg" alt="atf-1"/></a><a href="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2017/01/atf-3.jpg"><img src="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2017/01/atf-3.jpg" alt="atf-3"/></a><a href="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2017/01/atf-4.jpg"><img src="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/files/2017/01/atf-4.jpg" alt="atf-4"/></a></p>

**Comment by jvillalobos** [comment]
Hola, ¿como vamos con esta traducción?

**Comment by jvillalobos** [comment]
Voy a desasignarlo debido a que no ha habido respuesta.

**Comment by xexio** [comment]
Me la quedo y continuo con la traducción.

**Comment by xexio** [comment]
Lo dejo aquí para su revisión: https://gitlab.com/carlavilla/mozilla-translations/raw/master/Webgl2_lands_firefox.pdf

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/webgl-2-disponible-en-firefox/

Gracias!
