### ISSUE TITLE
ES6 In Depth: Symbols

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#12]
https://hacks.mozilla.org/2015/06/es6-in-depth-symbols/

**Comment by Josexv1** [comment]
Hola, voy a traducir esta. :)

**Comment by Josexv1** [comment]
Este aun no he logrado entregarlo, porque tuve problemas con mi disco duro. En unos 2 dias lo entrego que tenga todo de nuevo desde mi backup.

**Comment by Josexv1** [comment]
@jvillalobos ya termine esta traduccion, esta en el WP: https://www.mozilla-hispano.org/?p=39407&preview=true Solo hace falta editar codigo, y colocar algunas fotos.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/es6-en-detalle-simbolos/

Gracias!
