### ISSUE TITLE
Migrating to WebExtensions: port your stored data

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#121]
https://blog.mozilla.org/addons/2017/01/20/migrating-to-webextensions-port-your-stored-data/

**Comment by carloschocobar** [comment]
Hola jorge. Me gustaría traducir este artículo.

**Comment by carloschocobar** [comment]
Listo para revisión. https://docs.google.com/document/d/1lzC6HUqnOym-1Af2fG8TqCU9szyPXg_kfg4vsnp4e24/edit?usp=sharing

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/migrando-a-webextensions-mueve-tus-datos-almacenados/

Gracias!
