### ISSUE TITLE
WebAssembly Will Ease Collaboration on Next Generation Video Codecs

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#124]
https://hacks.mozilla.org/2017/02/webassembly-will-ease-collaboration-on-next-generation-video-codecs/

**Comment by jvadillo** [comment]
Hola Jorge . ¿ Puedes asignarme este artículo ?

**Comment by jvadillo** [comment]
@jvillalobos Ya tengo la traducción lista en: https://docs.google.com/document/d/1L7UZgWXtgCMgoSoWWn9j22Pg8u_C9czubCYcxXuvr8A/edit?usp=sharing

Un saludo!

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/webassembly-colaboracion-codecs-nueva-generacion/

Gracias!
