### ISSUE TITLE
Using Neutrino to jump-start modern JavaScript development

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#125]
https://hacks.mozilla.org/2017/02/using-neutrino-for-modern-javascript-development/

**Comment by parguello** [comment]
Continuaré con este artículo.
Un saludo.

**Comment by jvillalobos** [comment]
¿Cómo va la traducción de este artículo?

**Comment by parguello** [comment]
Hola Jorge, necesito revisarlo y pasarlo a WP esta semana.
Un saludo.

**Comment by parguello** [comment]
Listo para revisión.
Gracias!

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/usando-neutrino-iniciar-desarrollo-de-javascript-moderno/

Gracias!
