### ISSUE TITLE
Improving Themes in Firefox

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#127]
https://blog.mozilla.org/addons/2017/02/24/improving-themes-in-firefox/

**Comment by jordicuevas** [comment]
Beunas noches Jorge , anexo enlace de Google Docs para su revisión  

https://docs.google.com/document/d/1ksdYo__l4S3vvMyHViAIvjwFN4MXjFiHdqV75iyOs6k/edit?usp=sharing

Saludos!

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/mejorando-los-temas-en-firefox/

Gracias!
