### ISSUE TITLE
ES6 In Depth: Using ES6 today with Babel and Broccoli

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#13]
https://hacks.mozilla.org/2015/06/es6-in-depth-babel-and-broccoli/

**Comment by parguello** [comment]
Hola! 
Si os parece bien, puedo asignarme este post.
Un saludo :)

**Comment by parguello** [comment]
La traducción del artículo está listo en el siguiente enlace:
https://docs.google.com/document/d/1EZJKCDDtpdb38Mt-pn41dIQEskc7r4Yk1mEfw1DCp9Q/edit?usp=sharing
Gracias,
Un saludo.

**Comment by jvillalobos** [comment]
Publicado, gracias: https://www.mozilla-hispano.org/es6-en-detalle-es6-hoy-babel-broccoli/
