### ISSUE TITLE
Internationalize your keyboard controls

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#132]
https://hacks.mozilla.org/2017/03/internationalize-your-keyboard-controls/

**Comment by carloschocobar** [comment]
Hola Jorge. Me gustaría traducir este artículo.

**Comment by carloschocobar** [comment]
Listo para revisión. https://docs.google.com/document/d/1HfZG0LkBciXVJHnPUWH5qca-I1nzUAshHUWG3lk8MXg/edit?usp=sharing

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/internacionaliza-los-controles-del-teclado/

Gracias!
