### ISSUE TITLE
Developer Edition 54: New inspector and debugger features, MDN help in the netmonitor, and more

### ISSUE THREAD

**Issue by Skatox** [mozillahispano/blog-labs#133]
https://hacks.mozilla.org/2017/03/developer-edition-54-new-inspector-and-debugger-features/

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/edicion-desarrolladores-54-inspector-y-depurador-ayuda-de-mdn/

Gracias!
