### ISSUE TITLE
HTML5 Games Workshop: Make a platformer game with JavaScript!

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#134]
https://hacks.mozilla.org/2017/04/html5-games-workshop-make-a-platformer-game-with-javascript/

**Comment by jvadillo** [comment]
Hola Jorge . ¿ Puedes asignarme este artículo ?

**Comment by jvillalobos** [comment]
@jvadillo Le envié una invitación para unirse al grupo. Para empezar, mejor le asigno una de las dos tareas, en vez de las dos, así que avíseme cuál prefiere.

Gracias!

**Comment by jvadillo** [comment]
Muchas gracias @jvillalobos , puedes asignarme esta primero (https://hacks.mozilla.org/2017/04/html5-games-workshop-make-a-platformer-game-with-javascript/).
¿Donde puedo ver la invitación? No tengo ninguna notificación al respecto.
Gracias!

**Comment by jvillalobos** [comment]
Debería haber llegado por correo, y supongo que debería haber una notificación. Tal vez la pueda ver en esta página: https://github.com/orgs/mozillahispano/teams/blog-de-labs/members

**Comment by jvadillo** [comment]
Ya está, he entrado en el grupo. Gracias!

**Comment by jvadillo** [comment]
Ya tengo el artículo traducido. No conozco cual es la manera de subirlo, por lo que mientras lo he dejado disponible en el siguiente enlace: https://docs.google.com/document/d/1JT_eyHyL_6L0o8ats73d6dmcXpmwcDSwl9_i3mK0Y4g/edit?usp=sharing

Un saludo!

**Comment by jvillalobos** [comment]
En Google Docs está perfecto. Yo lo voy a revisar y publicar, lo cual puede tomar unas semanas. Si quiere puede ir escogiendo el artículo siguiente y se lo asigna.

Gracias!

**Comment by jvadillo** [comment]
Ok, ¡muchas gracias Jorge!

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/juegos-en-html5-juego-de-plataforma-con-javascript/

Gracias!
