### ISSUE TITLE
Hacking & Contributing to Servo On Windows

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#135]
https://hacks.mozilla.org/2017/04/hacking-contributing-to-servo-on-windows/

**Comment by parguello** [comment]
Hola Jorge, continuaré con este artículo.
Gracias!

**Comment by parguello** [comment]
Hola Jorge,

El artículo está listo para revision.
Te adjunto enlace a gdocs porque tengo problemas con el login a WP.
https://docs.google.com/document/d/1jNo7nufNniC5NSblfuRqtFht7L0JedrTGMMqqaLqvnA/edit?usp=sharing

Un saludo,

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/hackeo-y-colaboracion-para-servo-en-windows/

Gracias!
