### ISSUE TITLE
Replace Bootstrap Layouts with CSS Grid

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#136]
https://hacks.mozilla.org/2017/04/replace-bootstrap-layouts-with-css-grid/

**Comment by AngelFQC** [comment]
Pendiente de revisión

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/reemplaza-los-disenos-de-bootstrap-con-css-grid/

Gracias!
