### ISSUE TITLE
Simplifying Firefox Release Channels and Improving Developer Edition’s Stability

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#137]
https://hacks.mozilla.org/2017/04/simplifying-firefox-release-channels/

**Comment by siclemx** [comment]
Hola Jorge, tomaré este.

**Comment by jvillalobos** [comment]
Hola, ¿como vamos con esta traducción?

**Comment by siclemx** [comment]
Hola, lo había olvidado lo hago en esta semana y lo envío Jorge.


Saludos
Uriel

2017-07-08 11:13 GMT-05:00 Jorge Villalobos <notifications@github.com>:

**Comment by jvillalobos** [comment]
@BoSicle Ha habido progreso aquí?

**Comment by siclemx** [comment]
Hola, pensé que ya lo había enviado. https://docs.google.com/document/d/12JLzMxnFrS4Xm4oAQ0NYGgdpUQ3YDv-7cneZfnOKV5w/edit?usp=sharing

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/simplificando-los-canales-de-distribucion-de-firefox/

Gracias!
