### ISSUE TITLE
Why Rust is the Most Loved Language by Developers

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#138]
https://medium.com/mozilla-tech/why-rust-is-the-most-loved-language-by-developers-666add782563

**Comment by parguello** [comment]
Hola Jorge, me asignaré este artículo.
Un saludo.

**Comment by parguello** [comment]
Listo para revision en WP.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/por-que-rust-es-el-lenguaje-mas-querido-por-los-desarrolladores/

Gracias!
