### ISSUE TITLE
Fathom: a framework for understanding web pages

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#139]
https://hacks.mozilla.org/2017/04/fathom-a-framework-for-understanding-web-pages/

**Comment by jvadillo** [comment]
Traducido en: https://docs.google.com/document/d/1LZPd0EEWTw2tT1HoNchSQ87WSdp0BKr9s3RdAAzefOs/edit?usp=sharing

Es un artículo bastante complejo de traducir y revisar, llevará tiempo revisarlo.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/fathom-un-framework-para-entender-las-paginas-web/

Gracias!
