### ISSUE TITLE
ES6 In Depth: Collections

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#14]
https://hacks.mozilla.org/2015/06/es6-in-depth-collections/

**Comment by parguello** [comment]
Hola Jorge,
Me gustaria poder colaborar con el blog de labs. Si estas de acuerdo podria realizar la traduccion de este post.
Muchas gracias.
Un saludo.

**Comment by Josexv1** [comment]
Claro, @parguello cuando tengas la traduccion lista compartela en un etherpad o un Gdocs.

**Comment by parguello** [comment]
Hola,  el post está listo para ser revisado: https://docs.google.com/document/d/1gtbCbeztH1eGVgzjAr-IAVhSW3ENeBByqwO_0MDxjVk/edit?usp=sharing

Gracias
Un saludo.

**Comment by stripTM** [comment]
¿me podrías dar acceso para poder editar en el documento?

**Comment by parguello** [comment]
Sí,  por supuesto. Ya te he enviado el enlace.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/es6-en-detalle-colecciones/

Gracias!
