### ISSUE TITLE
Debugging Web Push in Mozilla Firefox

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#140]
https://hacks.mozilla.org/2017/05/debugging-web-push-in-mozilla-firefox/

**Comment by parguello** [comment]
Continuaré con esta traducción. Saludos

**Comment by jvillalobos** [comment]
Cómo va esta traducción?

**Comment by parguello** [comment]
Perdona el retraso Jorge, lo finalizare lo antes posible.

**Comment by parguello** [comment]
Listo para revision en WP. Gracias!

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/depurando-web-push-con-mozilla-firefox/

Gracias!
