### ISSUE TITLE
Quantum Up Close: What is a browser engine?

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#141]
https://hacks.mozilla.org/2017/05/quantum-up-close-what-is-a-browser-engine/

**Comment by xexio** [comment]
Me la quedo

**Comment by xexio** [comment]
Finalizado: https://gitlab.com/carlavilla/mozilla-translations/blob/master/quantum.pdf

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/quantum-de-cerca-motor-de-navegador-web/

Gracias!
