### ISSUE TITLE
Introducing FilterBubbler: A WebExtension built using React/Redux

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#143]
https://hacks.mozilla.org/2017/06/introducing-filterbubbler-a-webextension-built-using-reactredux/

**Comment by parguello** [comment]
Continuaré con este post.
Un saludo.

**Comment by jvillalobos** [comment]
¿Cómo va el progreso de esta traducción?

**Comment by parguello** [comment]
Hola Jorge,  el artículo está listo para revisión en Wordpress.  Gracias!

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/presentando-filterbubbler-una-webextension-construida-con-react-redux/

Gracias!
