### ISSUE TITLE
Cross-browser extensions, available now in Firefox

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#144]
https://hacks.mozilla.org/2017/06/cross-browser-extensions-available-now-in-firefox/

**Comment by jvadillo** [comment]
¡Hecho! Disponible en: https://docs.google.com/document/d/1TFgsr65Ejqha1R1kpXaseWO4rn5ag9xenjbWv8EoJyo/edit?usp=sharing

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/extensiones-multi-navegador-disponibles-ahora-en-firefox/

Gracias!
