### ISSUE TITLE
CSS Shapes, clipping and masking – and how to use them

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#145]
https://hacks.mozilla.org/2017/06/css-shapes-clipping-and-masking/

**Comment by carloschocobar** [comment]
Me gustaría traducir este artículo.

**Comment by carloschocobar** [comment]
https://docs.google.com/document/d/1Ad2W-PxjJTa5jRqmbtH5_4ykbYAWa1C2Hvd4b_xLGP0/edit?usp=sharing
Listo para revisión.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/css-shapes-clipping-masking-como-usarlos/

Gracias!
