### ISSUE TITLE
Firefox 54: E10S-Multi, WebExtension APIs, CSS clip-path

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#146]
https://hacks.mozilla.org/2017/06/firefox-54-e10s-webextension-apis-css-clip-path/

**Comment by jvadillo** [comment]
@jvillalobos Me lo asigno!

**Comment by jvadillo** [comment]
Listo! Disponible en: https://docs.google.com/document/d/1Mg5MGbkuvnKnAQpsfCYYWnJvZwjVxTHqSj85SRxaeYE/edit?usp=sharing

Un saludo!

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/firefox-54-e10s-multi-apis-de-webextensions-css-clip-path/

Este lo dejé fuera del blog principal porque el contenido es un poco viejo.

Gracias!
