### ISSUE TITLE
Inspect, Modify, and Debug React and Redux in Firefox with Add-ons

### ISSUE THREAD

**Issue by Skatox** [mozillahispano/blog-labs#147]
https://hacks.mozilla.org/2017/07/debug-react-redux-firefox-add-ons/

**Comment by Skatox** [comment]
https://www.mozilla-hispano.org/wp-admin/post.php?post=41233

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/inspecciona-modifica-depura-react-redux/

Gracias!
