### ISSUE TITLE
Firefox 55: first desktop browser to support WebVR

### ISSUE THREAD

**Issue by jvadillo** [mozillahispano/blog-labs#148]
https://hacks.mozilla.org/2017/08/firefox-55-supports-webvr/

**Comment by jvadillo** [comment]
Disponible en: https://docs.google.com/document/d/1FM9AeXQt1bTn2MyUjs9_mEgn7f-q4Bt1EdosPIVP10w/edit?usp=sharing

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/firefox-55-primer-navegador-con-soporte-webvr/

Gracias!
