### ISSUE TITLE
WebVR for All Windows Users

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#149]
https://hacks.mozilla.org/2017/08/webvr-for-all-windows-users/

**Comment by xexio** [comment]
Me la quedo

**Comment by xexio** [comment]
Lo dejo aquí para su revisión: https://gitlab.com/carlavilla/mozilla-translations/raw/master/WebVR_scarlavilla.pdf

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/webvr-para-todos-los-usuarios-de-windows/

Gracias!
