### ISSUE TITLE
Performance Testing Firefox OS With Raptor

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#15]
https://hacks.mozilla.org/2015/06/performance-testing-firefox-os-with-raptor/

**Comment by Josexv1** [comment]
Hola @jvillalobos voy a traducir este post, vale?

**Comment by jvillalobos** [comment]
Claro, adelante.

**Comment by jvillalobos** [comment]
Por cierto, la traducción la puede entregar como un Google Doc compartido. Gracias!

**Comment by Josexv1** [comment]
Vale, esta noche lo hago.

**Comment by Josexv1** [comment]
Hola, la traducción esta lista, solo falta acomodar acentos, y algún typo que se me haya pasado. Ya que no tengo el soporte a español aun.

https://www.dropbox.com/s/ntudsd2y7sjxhcb/Performance%20Testing%20Firefox%20OS%20With%20Raptor.odt?dl=0

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/rendimiento-firefox-os-con-raptor/

Gracias!
