### ISSUE TITLE
Intersection Observer comes to Firefox

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#150]
https://hacks.mozilla.org/2017/08/intersection-observer-comes-to-firefox/

**Comment by jvillalobos** [comment]
¿Cómo va el progreso de esta traducción?

**Comment by jvadillo** [comment]
Hola!

Todavía en progreso en: https://docs.google.com/document/d/17RAFXHjMVHUIn9HESZB-OzRkz6i_-pPjUPtBcNol2_s/edit#heading=h.c78arxnbffa7

Aviso cuando la finalice ;)

**Comment by jvillalobos** [comment]
Hola, ¿cómo va esta traducción?

**Comment by jvillalobos** [comment]
La regreso a pendiente por falta de respuesta.
