### ISSUE TITLE
Memory in WebAssembly (and why it’s safer than you think)

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#151]
https://hacks.mozilla.org/2017/07/memory-in-webassembly-and-why-its-safer-than-you-think/

**Comment by jvillalobos** [comment]
¿Cómo va el progreso de esta traducción?

**Comment by Skatox** [comment]
Hola, lo había olvidado. Acabo de hacerlo. Puedes chequear la traducción en https://www.mozilla-hispano.org/?p=41440

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/memoria-en-webassembly-mas-seguro-de-lo-que-piensas/

Gracias!
