### ISSUE TITLE
Introducing sphinx-js, a better way to document large JavaScript projects

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#153]
https://hacks.mozilla.org/2017/07/introducing-sphinx-js-a-better-way-to-document-large-javascript-projects/

**Comment by jvillalobos** [comment]
¿Cómo va el progreso de esta traducción?

**Comment by AngelFQC** [comment]
Lo había olvidado.
Este fin de semana está 😄

**Comment by AngelFQC** [comment]
Siento mucho la demora.
El artículo está para revisión

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/sphinx-js-mejor-forma-de-documentar-proyectos-javascript/

Gracias!
