### ISSUE TITLE
Powerful New Additions to the CSS Grid Inspector in Firefox Nightly

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#154]
https://hacks.mozilla.org/2017/06/new-css-grid-layout-panel-in-firefox-nightly/

**Comment by jvadillo** [comment]
He dejado la traducción en: https://docs.google.com/document/d/1fSZh5BkIV2E3J3QOZvpZ7oK_N-zY_IditVQxEchAW0U/edit?usp=sharing

**Comment by jvillalobos** [comment]
Será publicado mañana a esta hora en esta URL: https://www.mozilla-hispano.org/adiciones-al-css-grid-inspector-en-firefox/

Gracias!
