### ISSUE TITLE
Network Monitor Reloaded (Part 1)

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#155]
https://hacks.mozilla.org/2017/06/network-monitor-reloaded/

**Comment by xexio** [comment]
Me la quedo

**Comment by xexio** [comment]
Lo dejo aquí: https://gitlab.com/carlavilla/mozilla-translations/raw/master/network_monitor_reloaded.pdf

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/monitor-de-red-recargado-1/

Gracias!
