### ISSUE TITLE
Introducing the Extension Compatibility Tester

### ISSUE THREAD

**Issue by jvadillo** [mozillahispano/blog-labs#156]
Artículo original en: https://hacks.mozilla.org/2017/08/introducing-the-extension-compatibility-tester/

**Comment by jvadillo** [comment]
Traducido y listo para revisión: https://www.mozilla-hispano.org/wp-admin/post.php?post=41338&action=edit

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/presentacion-del-extension-compatibility-tester/

Gracias!
