### ISSUE TITLE
Building the DOM faster: speculative parsing, async, defer and preload

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#159]
https://hacks.mozilla.org/2017/09/building-the-dom-faster-speculative-parsing-async-defer-and-preload/

**Comment by jvillalobos** [comment]
Cómo va esta traducción?

**Comment by AngelFQC** [comment]
Dilcupe la demora 😄 
El artículo está para revisión

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/construyendo-el-dom-mas-rapido-analisis-especulativo-asincronico-diferido-y-precargado/

Gracias!
