### ISSUE TITLE
ES6 In Depth: Generators, continued

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#16]
https://hacks.mozilla.org/2015/07/es6-in-depth-generators-continued/

**Comment by jvillalobos** [comment]
Cuál es el estado de esta tarea?

**Comment by AngelFQC** [comment]
Ayer la retomé, me falta poco

**Comment by AngelFQC** [comment]
**Después de muchos meses, lo he terminado.**
Ahora tengo más tiempo para más posts

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/es6-en-detalle-generadores-continuacion/

¡Gracias!
