### ISSUE TITLE
WebAssembly table imports… what are they?

### ISSUE THREAD

**Issue by Skatox** [mozillahispano/blog-labs#162]
https://hacks.mozilla.org/2017/07/webassembly-table-imports-what-are-they/

**Comment by Skatox** [comment]
Traducido en https://www.mozilla-hispano.org/wp-admin/post.php?post=41557

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/tablas-de-importacion-de-webassembly-que-son/

Gracias!
