### ISSUE TITLE
Go beyond console.log with the Firefox Debugger

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#164]
https://hacks.mozilla.org/2017/11/go-beyond-console-log-with-the-firefox-debugger/

**Comment by xexio** [comment]
Me la quedo

**Comment by xexio** [comment]
Traducción: https://gitlab.com/carlavilla/mozilla-translations/blob/master/beyond_console_log_with_firefox_debugger.pdf

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/mas-alla-de-console-log-con-el-depurador/

Gracias!
