### ISSUE TITLE
New in Firefox 58: Developer Edition

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#167]
https://hacks.mozilla.org/2017/11/new-in-firefox-58-developer-edition/

**Comment by xexio** [comment]
Me la quedo

**Comment by xexio** [comment]
Traducción finalizada: https://gitlab.com/carlavilla/mozilla-translations/blob/master/new_firefox_58_developer.pdf

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/nuevo-en-firefox-58-developer-edition/

Gracias!
