### ISSUE TITLE
Creating a WebAssembly module instance with JavaScript

### ISSUE THREAD

**Issue by Skatox** [mozillahispano/blog-labs#168]
Había hecho traducción de este artículo: 
https://hacks.mozilla.org/2017/07/creating-a-webassembly-module-instance-with-javascript/

Y lo guardé en https://www.mozilla-hispano.org/wp-admin/post.php?post=41484&action=edit

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/creando-un-modulo-de-webassembly-con-javascript/

Gracias!
