### ISSUE TITLE
Entering the Quantum Era—How Firefox got fast again and where it’s going to get faster

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#169]
https://hacks.mozilla.org/2017/11/entering-the-quantum-era-how-firefox-got-fast-again-and-where-its-going-to-get-faster/

**Comment by Skatox** [comment]
Publicada en https://www.mozilla-hispano.org/entrando-a-la-era-quantum-como-firefox-volvio-a-ser-rapido-de-nuevo-y-como-se-hara-aun-mas/
