### ISSUE TITLE
ES6 In Depth: Proxies

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#17]
https://hacks.mozilla.org/2015/07/es6-in-depth-proxies-and-reflect/

**Comment by cruzgerardo3** [comment]
https://docs.google.com/document/d/1CKRUJhSFo42Un8FW6oQQjDIDTEanf7du9G6gbjPlK-8/edit?usp=sharing

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/es6-en-detalle-proxies/

Gracias!
