### ISSUE TITLE
Using Hardware Token-based 2FA with the WebAuthn API

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#173]
https://hacks.mozilla.org/2018/01/using-hardware-token-based-2fa-with-the-webauthn-api/

**Comment by fede3mmanuel** [comment]
Hello, Can i help with this article?

**Comment by jvillalobos** [comment]
Hola! Si está interesado en traducir el artículo a español, adelante :). La traducción la puede entregar usando Google Docs.

**Comment by fede3mmanuel** [comment]
Thank you very much, would it be to publish the article ?, to give permission to certain people? or what would be the way to send the translation ?, thanks

**Comment by jvillalobos** [comment]
Las instrucciones están en mi comentario. ¿Qué parte no está clara?

**Comment by fede3mmanuel** [comment]
Si ,lo leí, ¿solo que no entiendo si lo debo de publicar aquí?, ¿enviarselo a alguien o autorizar al alguien para que lo puedan editar (y revisar)?, ¿o solo ponerlo y lo copiaran para su revisión?, gracias

**Comment by jvillalobos** [comment]
Basta con que el documento esté público y ponga el link aquí.

**Comment by fede3mmanuel** [comment]
Hola esta es la traducción que realize:
https://docs.google.com/document/d/1zJdbdvv9v2UQFBmFvdb92mSvfFwhZv0eTxrdoOjRt6Q/edit?usp=sharing

**Comment by fede3mmanuel** [comment]
Hice modificaciones en base a la salida ve la versión 60 de Firefox

**Comment by jvillalobos** [comment]
Gracias, lo reviso pronto.

**Comment by jvillalobos** [comment]
Hola, parece que falta una sección. Hay dos ejemplos de código en el artículo. Falta el texto en medio de ellos.

Y una consulta: qué nombre quiere que aparezca en el crédito de traducción del artículo? Puede ser fede3mmanuel si así quiere, pero quisiera confirmarlo.

**Comment by fede3mmanuel** [comment]
Gracias por la revisión, creo que ya arregle el documento, de credito agradecería que pusíeran: "Emmanuel Sanchez", de antemano gracias

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/utilizando-dispositivos-2fa-con-la-api-webauthn/

Gracias!

**Comment by fede3mmanuel** [comment]
Ententido, muchas gracias :)
