### ISSUE TITLE
New in Firefox Developer Edition 61

### ISSUE THREAD

**Issue by Skatox** [mozillahispano/blog-labs#176]
https://hacks.mozilla.org/2018/05/new-in-firefox-61-developer-edition/

**Comment by xexio** [comment]
Hola,

¿Podría cogerla, se encuentra libre?

Un saludo.

**Comment by Skatox** [comment]
Si, tómala! no he tenido tiempo para hacerla.

**Comment by Skatox** [comment]
¿Has podido realizarla? Si no para asignarmela de nuevo.

**Comment by Skatox** [comment]
La he cerrado, ya está muy vieja la noticia
