### ISSUE TITLE
A cartoon intro to DNS over HTTPS

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#177]
https://hacks.mozilla.org/2018/05/a-cartoon-intro-to-dns-over-https/

**Comment by fede3mmanuel** [comment]
Hola, puedo realizar la traducción de este artículo?

**Comment by jvillalobos** [comment]
Claro, adelante.

**Comment by fede3mmanuel** [comment]
Excelente, gracias :)

**Comment by fede3mmanuel** [comment]
Listo para la primera revisión :)

https://docs.google.com/document/d/1AaenEj0PIBBz3G8d2o8ogkxvBM0knZe2tobJsXGbEK0/edit?usp=sharing

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/caricatura-dns-a-traves-de-https/

Gracias!
