### ISSUE TITLE
9 Biggest Mistakes with CSS Grid

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#182]
https://hacks.mozilla.org/2018/07/9-biggest-mistakes-with-css-grid/

**Comment by siclemx** [comment]
Hola, de este articulo hay que traducir también los nueve artículos que se mencionan o solo el principal?

**Comment by jvillalobos** [comment]
Solo el principal.

**Comment by siclemx** [comment]
Ok, lo tomo para traducirlo.

**Comment by siclemx** [comment]
Hola, lista la traducción.

https://docs.google.com/document/d/18cC1X3DXRYw6si-juHiX0ZNQXG4EhJAsIYeJHDpZNQU/edit?usp=sharing

**Comment by jvillalobos** [comment]
@siclemx El documento no está público, entonces no puedo verlo.

**Comment by siclemx** [comment]
Ups lo siento Jorge aquí está el enlace actualizado
https://docs.google.com/document/d/18cC1X3DXRYw6si-juHiX0ZNQXG4EhJAsIYeJHDpZNQU/edit?usp=sharing

Saludos
Uriel

**Comment by jvillalobos** [comment]
@siclemx Tengo el mismo problema con ese link. Envié una solicitud de acceso.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/los-9-errores-mas-comunes-al-usar-css-grid/

Gracias!
