### ISSUE TITLE
The Arch: Using Rust & WebAssembly to animate 30k colored LED lights

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#183]
https://hacks.mozilla.org/2018/07/the-arch-using-rust-webassembly-to-animate-30k-colored-led-lights/

**Comment by stripTM** [comment]
Estoy viendo que no tengo permiso para crear documentos en la carpeta de Hacks.Mozilla.org así que dejo la traducción en:
https://docs.google.com/document/d/1ant69SZSlTMQh6lMeZk4z5xflvWDMUdoFBQAw1nFXOc/edit?usp=sharing

Si resulta más cómodo puedo dejar el artículo en los borradores del wordpress de Mozilla Hispano.

**Comment by jvillalobos** [comment]
> Si resulta más cómodo puedo dejar el artículo en los borradores del wordpress de Mozilla Hispano.

Sí, eso es lo que me queda más conveniente. Gracias :)

**Comment by stripTM** [comment]
Listo, la dejo como borrador en https://www.mozilla-hispano.org/wp-admin/post.php?post=41791&action=edit

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/el-arco-rust-y-webassembly-30-mil-luces-led/

Gracias!
