### ISSUE TITLE
ES6 In Depth: let and const

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#19]
https://hacks.mozilla.org/2015/07/es6-in-depth-let-and-const/

**Comment by parguello** [comment]
Continuaré con este post si no hay inconveniente.
Un saludo.

**Comment by parguello** [comment]
La traducción está lista en el siguiente enlace:
https://docs.google.com/document/d/1RQ8XlUIo61gaDWdjNcJxDuAl7qGjgdsPar4w0gLvjrI/edit?usp=sharing

Gracias!
Un saludo.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/es6-en-detalle-let-y-const/

Gracias!
