### ISSUE TITLE
JavaScript Errors and How to Fix Them

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#2]
http://davidwalsh.name/fix-javascript-errors

**Comment by MaGo15** [comment]
Hola Jorge por que no aparece asignado este articulo, yo lo estoy traduciendo, tarde pero seguro

**Comment by jvillalobos** [comment]
@MaGo15 le envié una invitación por correo para unirse a los colaboradores de este grupo, y parece que no ha respondido todavía. Por eso no le he podido asignar la tarea. Me avisa si ocupa que la envíe de nuevo.

En todo caso nadie le va a quitar la tarea ;)

**Comment by MaGo15** [comment]
Ya estamos aquí!!!!!!!! :+1:

**Comment by MaGo15** [comment]
Jorge termine por fin el articulo no había podido dedicarme a el, pero bueno ya te lo compartí.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/errores-en-javascript-y-como-solucionarlos/

Gracias!
