### ISSUE TITLE
How fast are web workers?

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#20]
https://hacks.mozilla.org/2015/07/how-fast-are-web-workers/

**Comment by fjaguero** [comment]
Podría tomar este si les parece.

**Comment by fjaguero** [comment]
Paso la traducción: https://docs.google.com/document/d/15EI9vS6CIGuaREZuRZzBEMqyyI8NOV_Fv4e0jfo3oQI/edit?usp=sharing

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/que-tan-rapidos-son-los-web-workers/

Gracias!
