### ISSUE TITLE
Build an HTML5 game—and distribute it

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#21]
https://hacks.mozilla.org/2015/06/build-an-html5-game-and-distribute-it/

**Comment by omarseguvi** [comment]
@jvillalobos  Puedo empezar con este?? soy nuevo disculpa el incoveniente. Me gustaría saber si me puede ayudar con esto es que estoy iniciando... entonces para ver las cosas básicas, donde se edita el documento donde lo envía  ese tipo de cosas. Gracias

**Comment by jvillalobos** [comment]
Sí, adelante. La traducción la puede hacer en Google Docs (no hace falta incluir imágenes o vídeos) y luego nos la comparte aquí.

**Comment by omarseguvi** [comment]
Listo aquí está la traducción me avisa si hay que cambiarle algo, como es el primero que hago.
Gracias.
https://docs.google.com/document/d/1rzFh6qVY94fHLQ37wLzxNpIeItDAGNVEPqk6x8QSXMY/edit?usp=sharing

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/crear-un-juego-en-html5-y-distribuirlo/. Gracías!

Un par de notas: tratar de mantener el "tú" y no usar "usted". Los nombres propios de tecnologías es mejor mantenerlos en inglés. "Firefox" en vez de "FireFox".

Si quiere traducir otro, nada más tome alguno de la lista de Pendientes.

**Comment by omarseguvi** [comment]
2015-10-11 12:48 GMT-06:00 Jorge Villalobos notifications@github.com:

**Comment by omarseguvi** [comment]
Gracias... perfecto lo tomaré en cuenta....!

2015-10-11 20:18 GMT-06:00 Omar Segura omarseguvi@gmail.com:
