### ISSUE TITLE
Developer Edition 42: Wifi Debugging, Win10, Multiprocess Firefox, ReactJS tools, and more

### ISSUE THREAD

**Issue by Skatox** [mozillahispano/blog-labs#22]
Traducción del artículo https://hacks.mozilla.org/2015/08/developer-edition-42-wifi-debugging-win10-multiprocess-firefox-reactjs-tools-and-more/

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/firefox-para-desarrolladores-42-depuracion-de-wifi-multiproceso-reactjs-y-mas/

Gracias!

**Comment by pochy-ja** [comment]
Muy interesante el artículo, solo señalar algo que para mi entender pierde un poco la concordancia, en el artículo cuando se habla del multiproceso, la frase dice así "Si experiencias algún problema con complementos", al parecer se les a quedado al traducir el artículo, creo que querían decir "Si experimentas algún problema con los complementos".

Saludos

**Comment by Skatox** [comment]
Gracias por la sugerencia, lo he corregido.
