### ISSUE TITLE
Flash-Free Clipboard for the Web

### ISSUE THREAD

**Issue by Josexv1** [mozillahispano/blog-labs#23]
Traduccion de este tema, lista para su revision.
https://hacks.mozilla.org/2015/09/flash-free-clipboard-for-the-web/

https://www.mozilla-hispano.org/?p=39229&preview=true

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/portapapeles-para-la-web-sin-flash/

Gracias!
