### ISSUE TITLE
Usar el Hackerplace sin resetear el teléfono

### ISSUE THREAD

**Issue by stripTM** [mozillahispano/blog-labs#24]
Crear artículo con la información de este hilo https://foro.mozilla-hispano.org/t/usar-el-hackerplace-sin-resetear-el-telefono/21019

**Comment by stripTM** [comment]
En borrador listo para revisar y publicar.

https://www.mozilla-hispano.org/?p=39295&preview=true

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/usar-el-hackerplace-sin-resetear-el-telefono/

Gracias!
