### ISSUE TITLE
Instalar Firefox OS en un Nexus 5

### ISSUE THREAD

**Issue by iFrey** [mozillahispano/blog-labs#25]

**Comment by iFrey** [comment]
https://foro.mozilla-hispano.org/t/firefox-os-en-nexus-5/21199

**Comment by fjaguero** [comment]
¿La idea es hacer un artículo de esto?

**Comment by pochy-ja** [comment]
sería interesante, si alguien no lo toma podría hacerlo yo!

**Comment by iFrey** [comment]
Perdón por el retraso, pero si la idea es que se hiciera como un artículo. Y por mi parte puedes hacerlo, ya que yo no puedo.

**Comment by Skatox** [comment]
¿Vale la pena seguir haciendo este artículo? por lo que ya no habrá #FirefoxOS para teléfonos

**Comment by fjaguero** [comment]
+1 @Skatox

**Comment by Josexv1** [comment]
Creo que ya no haría falta este issue, ya que no se le dara continuidad a la versión para smartphones.

**Comment by fjaguero** [comment]
Lo dejo cerrado entonces @jvillalobos
