### ISSUE TITLE
Pointer Events now in Firefox Nightly

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#27]
https://hacks.mozilla.org/2015/08/pointer-events-now-in-firefox-nightly/

**Comment by JoelBuenrostro** [comment]
Saludos
me gustaría colaborar con este post

**Comment by JoelBuenrostro** [comment]
Me tome la libertad de empezarlo, dejo el borrador para revisión.

https://docs.google.com/document/d/1qwjDBKB0soMPN5483QFR3jbmK7zjnTuLbKmocFeCC9I/edit?usp=sharing

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/eventos-de-puntero-en-firefox/

Gracias!
