### ISSUE TITLE
ES6 In Depth: Subclassing

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#28]
https://hacks.mozilla.org/2015/08/es6-in-depth-subclassing/

**Comment by parguello** [comment]
Me gustaría continuar con este post. Gracias :)

**Comment by parguello** [comment]
El artículo está listo en el siguiente enlace:
https://docs.google.com/document/d/18vBI1XkDKDrbH4m1Z3Jv1LNQK5ZJbi0TU8wGF5w92JA/edit?usp=sharing

Un saludo.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/es6-en-detalle-subclases/

Gracias!
