### ISSUE TITLE
ES6 In Depth: Modules

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#29]
https://hacks.mozilla.org/2015/08/es6-in-depth-modules/

**Comment by whitmanttwnew** [comment]
puedo trabajar en este si me lo permiten

**Comment by jvillalobos** [comment]
Listo. Le envié una invitación al grupo para poder asignarle bien la tarea.

**Comment by jvillalobos** [comment]
@whitmanttwnew hay alguna actualización con respecto a esta tarea?

**Comment by jordicuevas** [comment]
Buenas tardes me gustaría trabajar en esta traducción si esta disponible. gracias!

**Comment by jvillalobos** [comment]
Sí, está disponible. Adelante! La puede entregar con un Google Doc.

**Comment by jordicuevas** [comment]
Buenas noches anexo la traducción para su revisión https://docs.google.com/document/d/12lpih3uxcGd_YJfM3bZgbZd8urw6971t8Wtm6vKfXKE/edit?usp=sharing

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/es6-en-detalle-modulos/

Gracias!
