### ISSUE TITLE
Introducing @counter-style

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#3]
http://hacks.mozilla.org/2015/02/introducing-counter-styles/

**Comment by AngelFQC** [comment]
[En pendiente de resivión](https://www.mozilla-hispano.org/wp-admin/post.php?post=29778&action=edit)
Favor de agregarle sintaxis CSS @jvillalobos

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/introduccion-a-counter-style/
Gracias!
