### ISSUE TITLE
ES6 In Depth: The Future

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#30]
https://hacks.mozilla.org/2015/08/es6-in-depth-the-future/

**Comment by omarseguvi** [comment]
Me gustaría traducir este! :+1:

**Comment by omarseguvi** [comment]
Perdón por la tardanza, es que estaba en fin de semestre... aquí está la traducción, puedo empezar con otro de una vez?
https://docs.google.com/document/d/1P5iYmz_T3ZRPGuXP7I51vLz6YqC6HnCeJPKCCUzBmdA/edit?usp=sharing

**Comment by jvillalobos** [comment]
Sí, puede tomar cualquiera de los pendientes.

**Comment by jvillalobos** [comment]
Publicado (después de mil años): https://www.mozilla-hispano.org/es6-en-detalle-el-futuro/

Gracias!
