### ISSUE TITLE
Let’s Write a Web Extension

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#31]
https://hacks.mozilla.org/2015/09/lets_write_a_webextension/

**Comment by AngelFQC** [comment]
La pido :smile:

**Comment by jvillalobos** [comment]
Bienvenido de vuelta :). Por cierto, le envié una invitación al grupo, para así poderle asignar las tareas. Me avisa si no la tiene.

**Comment by AngelFQC** [comment]
Gracías! :)
No me ha llegado la invitación

**Comment by AngelFQC** [comment]
Pendiente de revisión
Favor de aplicar la sintaxis de JavaScript

**Comment by AngelFQC** [comment]
Podrían asignarme permisos para agregar la sintaxis y publicar?

**Comment by jvillalobos** [comment]
Publicada, gracias: https://www.mozilla-hispano.org/escribamos-una-webextension/

(No sé cómo está el asunto de los permisos, los administradores deberían saber).
