### ISSUE TITLE
Building RTL-Aware Web Apps & Websites: Part 1

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#32]
https://hacks.mozilla.org/2015/09/building-rtl-aware-web-apps-and-websites-part-1/

**Comment by carloschocobar** [comment]
Hola Jorge. Soy carlos chocobar y me gustaría traducir este artículo. Gracias.

**Comment by jvillalobos** [comment]
Hola Carlos. Le envié una invitación al grupo para poder asignarle la tarea. Gracias!

**Comment by carloschocobar** [comment]
[Creando RTL.docx](https://github.com/mozillahispano/blog-labs/files/37114/Creando.RTL.docx)
Pendiente de revisión. No sabía cómo subir la traducción, así que la adjunté al comentario.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/web-apps-y-sitios-web-rtl-1/

Gracias!
