### ISSUE TITLE
Porting Chrome Extensions to Firefox with WebExtensions

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#33]
https://hacks.mozilla.org/2015/10/porting-chrome-extensions-to-firefox-with-webextensions/

**Comment by AngelFQC** [comment]
La pido :)
Estoy con otra de WebExtensions

**Comment by AngelFQC** [comment]
Pendiente de resivisón
Por favor, agregar la sintaxis de JS

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/portando-extensiones-de-chrome-con-webextensions/

Gracias!
