### ISSUE TITLE
Inspecting Security and Privacy Settings of a Website

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#34]
https://hacks.mozilla.org/2015/10/inspecting-security-and-privacy-settings-of-a-website/

**Comment by ElPardo** [comment]
Quiero colaborar con este artículo

**Comment by jvillalobos** [comment]
Adelante! Nos puede pasar la traducción usando Google Docs, o cualquier otra manera que prefiera. Le voy a enviar una invitación para unise a nuestro grupo, y así le puedo asignar la tarea.

Gracias!

**Comment by ElPardo** [comment]
Muchas gracias Jorge, Feliz día

**Comment by ElPardo** [comment]
Hola jorge ya tengo el artículo, como te lo puedo enviar?

**Comment by jvillalobos** [comment]
Lo puede compartir por medio de Google Docs, o ponerlo aquí como un adjunto.

**Comment by ElPardo** [comment]
hola jorge te comparto el artículo traducido para su revisión.
[inspeccionando config web.docx](https://github.com/mozillahispano/blog-labs/files/78622/inspeccionando.config.web.docx)

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/inspeccionando-seguridad-y-privacidad-de-un-sitio-web/

Gracias!
