### ISSUE TITLE
Building RTL-Aware Web Apps & Websites: Part 2

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#35]
https://hacks.mozilla.org/2015/10/building-rtl-aware-web-apps-websites-part-2/

**Comment by ruthhernandez1** [comment]
¡Buenas tardes! Si lo tiene a bien, puedo traducir este artículo también. Por favor confirmarme. Gracias.

**Comment by jvillalobos** [comment]
@ruthhernandez1 Ha habido progreso con esta tarea?

**Comment by ruthhernandez1** [comment]
Hola:

Por favor reasignarlo.

Saludos,

Ruth

**Comment by SoftwareRVG** [comment]
Jorge , lo siento , no estaba al corriente de que  tarea estaba pendiente. He cogido la de realidad virtual. Esperi que no te importe. Cuando la cogí esta tarea no estaba en pendientes.

saludos a todos @SoftwareRVG

**Comment by parguello** [comment]
Hola,
Me asigno este artículo, ya que está en estado pendiente. 
Un saludo. :)

**Comment by parguello** [comment]
Hola! El artículo está listo para revisión en WordPress.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/creando-web-apps-y-sitios-web-compatibles-con-rtl-parte-2/

Gracias!
