### ISSUE TITLE
HTML 5 games: Tilemaps

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#36]
https://hacks.mozilla.org/2015/10/html-5-games-tilemaps/

**Comment by omarseguvi** [comment]
este (y)

**Comment by omarseguvi** [comment]
Listo.... 
https://docs.google.com/document/d/1owfJSxnDJOi5hdZRCcfNpGAaE26wchmSVhXQFyMzYao/edit?usp=sharing

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/juegos-html5-tilemaps/

Gracias!
