### ISSUE TITLE
Keep pushing it, with the W3C Push API

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#37]
https://hacks.mozilla.org/2015/10/keep-pushing-it-with-the-w3c-push-api/

**Comment by parguello** [comment]
Hola,

Me gustaría continuar con este post si os parece bien.

Gracias,
Un saludo.

**Comment by parguello** [comment]
El documento está listo en:
https://docs.google.com/document/d/1piaxkBCQQbmzeqCpYJ_pfStbpT_vZPQV814L63id6LM/edit?usp=sharing

Un saludo.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/sigue-empujando-api-w3c-push/

Gracias!
