### ISSUE TITLE
HTML5 games: 3D collision detection

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#39]
https://hacks.mozilla.org/2015/10/html-5-games-3d-collision-detection/

**Comment by omarseguvi** [comment]
Si quiere me asignan este... gracias

**Comment by omarseguvi** [comment]
Listo 
https://docs.google.com/document/d/19XeFiBFoXE-igWIHN4tndRD7VjmRSqdd_56sENUxwO8/edit?usp=sharing

**Comment by jvillalobos** [comment]
Publicado, gracias! https://www.mozilla-hispano.org/juegos-html5-colisiones-3d/
