### ISSUE TITLE
Pixel Perfect 2: extension for Firefox Developer Tools

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#4]
https://hacks.mozilla.org/2015/03/pixel-perfect-2-extension-for-firefox-developer-tools/

**Comment by fjaguero** [comment]
En vistas al objetivo de promover las Developer Tools, podría encargarme de traducir esta, ¿cómo lo ves? @jvillalobos

**Comment by jvillalobos** [comment]
Las tareas "en progreso" ya tienen dueño, pero todavía no las he asignado porque los dueños todavían no han aceptado la invitación al equipo.

**Comment by fjaguero** [comment]
Perfecto, lo comenté al no ver un assignee.

**Comment by siclemx** [comment]
Listo! https://docs.google.com/document/d/1cLLv76cw6Csk2M7N3FtZ6519FxNhUmbjj4lMVXDEj0w/edit?usp=sharing

**Comment by jvillalobos** [comment]
Publicado: http://www.mozilla-hispano.org/pixel-perfect-2-extension-para-desarrollador/

Gracias!
