### ISSUE TITLE
Revisiting Firefox’s DevTools

### ISSUE THREAD

**Issue by AngelFQC** [mozillahispano/blog-labs#44]
http://www.smashingmagazine.com/2015/12/revisiting-firefox-devtools/

**Comment by parguello** [comment]
Hola! Me gustaría continuar con la traducción de este artículo. 
Un saludo.

**Comment by parguello** [comment]
Adjunto el link con la traducción:
https://docs.google.com/document/d/1ukBPcMkulJyjVcxqejivAG19C_14bXfAtx1-fz8nn6s/edit?usp=sharing

Nota: he incluido los links de youtube con los vídeos para insertar.
Un saludo.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/revision-herramientas-de-desarrollo-de-firefox/

¡Gracias!
