### ISSUE TITLE
Firefox’s New Memory Tool

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#47]
https://hacks.mozilla.org/2015/11/firefoxs-new-memory-tool/

**Comment by Josexv1** [comment]
@Skatox estas traduciendo este?

**Comment by Skatox** [comment]
No, no estoy traduciendo ese artículo.

**Comment by Josexv1** [comment]
Listo, lo tomo yo entonces.

**Comment by Josexv1** [comment]
Lamento la tardanza, acabo de terminar este tema. Una cosa no supe como traducir: **coarse type**, así que lo deje de esa forma.

https://www.mozilla-hispano.org/?p=40021&preview=true

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/la-nueva-herramienta-de-memoria-de-firefox/, gracias!
