### ISSUE TITLE
Compiling to WebAssembly: It’s Happening!

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#48]
https://hacks.mozilla.org/2015/12/compiling-to-webassembly-its-happening/

**Comment by parguello** [comment]
Hola! Si os parece bien, me asignaré este artículo para traducir.
Un saludo.

**Comment by parguello** [comment]
Listo en: https://docs.google.com/document/d/142bJvnULfxTucfUSmezuM2BvbagP8CIkt0tIN-Wxgr4/edit?usp=sharing

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/compilando-a-webassembly-esta-sucediendo/

Gracias!
