### ISSUE TITLE
Developer Edition 45 – Animations, Memory Tools and More

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#49]
https://hacks.mozilla.org/2015/12/developer-edition-45-animations-memory-tools-and-more/

**Comment by Skatox** [comment]
Traducido, disculpa si lo pongo muy arriba en la lista de pendientes en waflle, es que este artículo es viejo y pronto debe venir el de 46

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/firefox-para-desarrolladores-45-animaciones-memoria-y-mas/

Gracias!
