### ISSUE TITLE
Beyond Offline

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#52]
https://hacks.mozilla.org/2015/12/beyond-offline/

**Comment by SoftwareRVG** [comment]
Hola Jorge

¿Puedes asignarme esta traducción?. Respecto a la anterior la he pasado a revisión. Era mi primera tarea. Si hay algun paso, enlace ,documento,u otra acción que realizeis de otro modo al que yo lo he hecho, me lo dices para aplicarlo en mis siguientes tareas. 

Saludos. Rober Villar

**Comment by Josexv1** [comment]
@SoftwareRVG trata de enviar la traducción en un Documento de Google, para que sea mas fácil de editar. Editas, y publicas el link aca.

**Comment by SoftwareRVG** [comment]
De acuerdo. El anterior lo he pasado en google docks tambien. en el último comentario que he hecho está el enlace.  Aqui  tienes el de DevTools Reload _publicacion de Soledad Penadés:
https://docs.google.com/document/d/1Vnx8XOT0LJU6Xc_W-sKsssZaPps_9pQcpCJmC3_7SJo/edit?usp=sharing
Gracias Jose . 

Saludos  Rober Villar

**Comment by SoftwareRVG** [comment]
<h1 class="post__title">Mas allá, sin conexión</h1>

  <div class="byline">
    <h3 class="post__author">
                      <img alt='' src='https://secure.gravatar.com/avatar/51e4f6459f94a04520ee141daeed3af0?s=64&#038;d=mm&#038;r=g' srcset='https://secure.gravatar.com/avatar/51e4f6459f94a04520ee141daeed3af0?s=128&amp;d=mm&amp;r=g 2x' class='avatar avatar-64 photo' height='64' width='64' />        Por
                                        <a class="url" href="http://unoyunodiez.com" rel="external me">Salva</a>                            </h2>
    <div class="post__meta">
      Publicado el
      <abbr class="published" title="2015-12-21T12:23:56-08:00">
        21 Diciembre, 2015      </abbr>
      <span class="entry-cat">en
        <a href="https://hacks.mozilla.org/category/serviceworkers/" rel="category tag" title="View all posts in ServiceWorkers" >ServiceWorkers</a>      </span>
            <div class="socialshare" data-type="bubbles"></div>
    </div>
  </div>
</div>

<main id="content-main" class="section article">
  <article class="post" role="article">
    <p>Esta es mi primera publicación en Mozilla,y aparte de mi blog personal , esta es mi primera publicación como mozillian (yay!). Durante este mes he estado trabajando en el <a href="https://serviceworke.rs/" target="_blank">Service Worker Cookbook project</a> —parte de el <a href="https://wiki.mozilla.org/Apps" target="_blank">Web Application Developer Initiative</a> (WADI)— Que me ha dado la oportunidad de poner mi experiencia en ServicesWorkers a la práctica mientras que al mismo tiempo aprendía nuevas maneras de aprovechar esta excitante nueva tecnología web para el bien de la Web. Permitidme compartir con vosotros algunos de mis últimos pensamientos.</p>

<p>En la publicación previa de esta serie participó mi compañero <a href="http://davidwalsh.name/" target="_blank">David Walsh</a> hablando sobre <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache" target="_blank">Caché de Aplicación</a> y su falta de flexibilidad,por lo que no voy a profundizar mas en este tema. Sin embargo revisaré algo mas las recetas disponibles  en el Service Worker Cookbook. David lo presentó y explicó algunas  <a href="https://hacks.mozilla.org/2015/11/offline-service-workers/" target="_blank">recetas fuera de linea</a>; Yo quiero ir un poco mas allá y ver algunos otros usos de Service Workers.</p>

<h2>Service workers hoy</h2>

**Comment by SoftwareRVG** [comment]
<h1 class="post__title">Mas allá, sin conexión</h1>

  <div class="byline">
    <h3 class="post__author">
                      <img alt='' src='https://secure.gravatar.com/avatar/51e4f6459f94a04520ee141daeed3af0?s=64&#038;d=mm&#038;r=g' srcset='https://secure.gravatar.com/avatar/51e4f6459f94a04520ee141daeed3af0?s=128&amp;d=mm&amp;r=g 2x' class='avatar avatar-64 photo' height='64' width='64' />        Por
                                        <a class="url" href="http://unoyunodiez.com" rel="external me">Salva</a>                            </h2>
    <div class="post__meta">
      Publicado el
      <abbr class="published" title="2015-12-21T12:23:56-08:00">
        21 Diciembre, 2015      </abbr>
      <span class="entry-cat">en
        <a href="https://hacks.mozilla.org/category/serviceworkers/" rel="category tag" title="View all posts in ServiceWorkers" >ServiceWorkers</a>      </span>
            <div class="socialshare" data-type="bubbles"></div>
    </div>
  </div>
</div>

<main id="content-main" class="section article"> 
  <article class="post" role="article">
    <p>Esta es mi primera publicación en Mozilla,y aparte de mi blog personal , esta es mi primera publicación como mozillian (yay!). Durante este mes he estado trabajando en el <a href="https://serviceworke.rs/" target="_blank">Service Worker Cookbook project</a> —parte de el <a href="https://wiki.mozilla.org/Apps" target="_blank">Web Application Developer Initiative</a> (WADI)— Que me ha dado la oportunidad de poner mi experiencia en ServicesWorkers a la práctica mientras que al mismo tiempo aprendía nuevas maneras de aprovechar esta excitante nueva tecnología web para el bien de la Web. Permitidme compartir con vosotros algunos de mis últimos pensamientos.</p>

<p>En la publicación previa de esta serie participó mi compañero <a href="http://davidwalsh.name/" target="_blank">David Walsh</a> hablando sobre <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache" target="_blank">Caché de Aplicación</a> y su falta de flexibilidad,por lo que no voy a profundizar mas en este tema. Sin embargo revisaré algo mas las recetas disponibles  en el Service Worker Cookbook.. David lo presentó y explicó algunas  <a href="https://hacks.mozilla.org/2015/11/offline-service-workers/" target="_blank">recetas fuera de linea</a>; Yo quiero ir un poco mas alla y ver algunos otros usos de Service Workers.</p>

<h2>Service workers hoy</h2>

<p>A pesar de haber estado en desarrollo durante algún tiempo,solo ahora comenzamos a escuchar que<a href="https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API" target="_blank"> Service Workers</a> está siendo utilizado líbremente. En resumen, esta API fué entregada originalmente para corregir lo que el caché de la aplicación hacía mal. <a href="https://github.com/slightlyoff/ServiceWorker/tree/63a184996d1fd199dea8e922b6edbd1fd4642748#whats-going-on-here" target="_blank">la arqueología web</a> revela que la intención fué precisamente fijar caché fuera de linea, permitiendo a los desarrolladores web<q>construir URL amigable,por defecto aplicaciones fuera de linea por capas de una manera fiable.</q>.</p>

<p>El planteamiento inicial introdujo el concepto de control de la navegación a través de un concepto que se desarrolló dentro de Service Worker’s <a href="https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent" target="_blank">recuperar la funcionalidad en el acto</a>: una manera de interceptar solicitudes de red y dar respuesta con los datos obtenidos, bases de datos o procedimiento generado. ¿La mejor parte? Las páginas controladas no tienen que saber que en realidad están siendo pirateadas (a pesar de que se les puede decir) por lo que la lógica  del servicio está complétamente disociada de la lógica de la aplicación. Un perfecto “intermediario”.</p>

<p>Pero como hackers (¡Este es el blog Hacks, después de todo!) Lo que nos gusta es elaborar soluciones ingeniosas a problemas relevantes en los que “ingeniosas” con frecuencia significa abusar de las intenciones reales de algo. En Mozilla, desde nuestras iniciativas WADI y Firefox OS estamos explorando los siguientes usos con etiqueta-desconectado de Service Workers.</p>

<h2>API analítica</h2>

<p>Vamos a comenzar con una aplicación directa del intermediario: <strong><a href="https://serviceworke.rs/api-analytics.html" target="_blank">API analytics</a></strong>. Imagina que deseas obtener estádistica de una API y no tienes acceso al servidor. Las soluciones actuales  manipulan la solicitud del cliente generando código HTTP , enviando los registros apropiados al servicio de analítica. Un Service Worker puede ir mas allá, interceptando cada solicitud, extrayendo los parámetros, y enviando el registro para analizar permitiendo que la solicitud original alcance la red.</p>

<h2>Instalación de APPS empaquetadas</h2>

**Comment by SoftwareRVG** [comment]
### Jorge, llevo la traducción bastante avanzada,mañana espero tenerla preparada. La pasaré a revisión  con un enlace de Google Docks  aquí en GitHub y te envio un  correo también con el enlace.

---

<h1 class="post__title">Mas allá, sin conexión</h1>

  <div class="byline">
    <h3 class="post__author">
                      <img alt='' src='https://secure.gravatar.com/avatar/51e4f6459f94a04520ee141daeed3af0?s=64&#038;d=mm&#038;r=g' srcset='https://secure.gravatar.com/avatar/51e4f6459f94a04520ee141daeed3af0?s=128&amp;d=mm&amp;r=g 2x' class='avatar avatar-64 photo' height='64' width='64' />        Por
                                        <a class="url" href="http://unoyunodiez.com" rel="external me">Salva</a>                            </h2>
    <div class="post__meta">
      Publicado el
      <abbr class="published" title="2015-12-21T12:23:56-08:00">
        21 Diciembre, 2015      </abbr>
      <span class="entry-cat">en
        <a href="https://hacks.mozilla.org/category/serviceworkers/" rel="category tag" title="View all posts in ServiceWorkers" >ServiceWorkers</a>      </span>
            <div class="socialshare" data-type="bubbles"></div>
    </div>
  </div>
</div>

<main id="content-main" class="section article"> 
  <article class="post" role="article">
    <p>Esta es mi primera publicación en Mozilla,y aparte de mi blog personal , esta es mi primera publicación como mozillian (yay!). Durante este mes he estado trabajando en el <a href="https://serviceworke.rs/" target="_blank">Service Worker Cookbook project</a> —parte de el <a href="https://wiki.mozilla.org/Apps" target="_blank">Web Application Developer Initiative</a> (WADI)— Que me ha dado la oportunidad de poner mi experiencia en ServicesWorkers a la práctica mientras que al mismo tiempo aprendía nuevas maneras de aprovechar esta excitante nueva tecnología web para el bien de la Web. Permitidme compartir con vosotros algunos de mis últimos pensamientos.</p>

<p>En la publicación previa de esta serie participó mi compañero <a href="http://davidwalsh.name/" target="_blank">David Walsh</a> hablando sobre <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache" target="_blank">Caché de Aplicación</a> y su falta de flexibilidad,por lo que no voy a profundizar mas en este tema. Sin embargo revisaré algo mas las recetas disponibles  en el Service Worker Cookbook.. David lo presentó y explicó algunas  <a href="https://hacks.mozilla.org/2015/11/offline-service-workers/" target="_blank">recetas fuera de linea</a>; Yo quiero ir un poco mas alla y ver algunos otros usos de Service Workers.</p>

<h2>Service workers hoy</h2>

<p>A pesar de haber estado en desarrollo durante algún tiempo,solo ahora comenzamos a escuchar que<a href="https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API" target="_blank"> Service Workers</a> está siendo utilizado líbremente. En resumen, esta API fué entregada originalmente para corregir lo que el caché de la aplicación hacía mal. <a href="https://github.com/slightlyoff/ServiceWorker/tree/63a184996d1fd199dea8e922b6edbd1fd4642748#whats-going-on-here" target="_blank">la arqueología web</a> revela que la intención fué precisamente fijar caché fuera de linea, permitiendo a los desarrolladores web<q>construir URL amigable,por defecto aplicaciones fuera de linea por capas de una manera fiable.</q>.</p>

<p>El planteamiento inicial introdujo el concepto de control de la navegación a través de un concepto que se desarrolló dentro de Service Worker’s <a href="https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent" target="_blank">recuperar la funcionalidad en el acto</a>: una manera de interceptar solicitudes de red y dar respuesta con los datos obtenidos, bases de datos o procedimiento generado. ¿La mejor parte? Las páginas controladas no tienen que saber que en realidad están siendo pirateadas (a pesar de que se les puede decir) por lo que la lógica  del servicio está complétamente disociada de la lógica de la aplicación. Un perfecto “intermediario”.</p>

<p>Pero como hackers (¡Este es el blog Hacks, después de todo!) Lo que nos gusta es elaborar soluciones ingeniosas a problemas relevantes en los que “ingeniosas” con frecuencia significa abusar de las intenciones reales de algo. En Mozilla, desde nuestras iniciativas WADI y Firefox OS estamos explorando los siguientes usos con etiqueta-desconectado de Service Workers.</p>

<h2>API analítica</h2>

<p>Vamos a comenzar con una aplicación directa del intermediario: <strong><a href="https://serviceworke.rs/api-analytics.html" target="_blank">API analytics</a></strong>. Imagina que deseas obtener estádistica de una API y no tienes acceso al servidor. Las soluciones actuales  manipulan la solicitud del cliente generando código HTTP , enviando los registros apropiados al servicio de analítica. Un Service Worker puede ir mas allá, interceptando cada solicitud, extrayendo los parámetros, y enviando el registro para analizar permitiendo que la solicitud original alcance la red.</p>

<h2>Instalar APPS empaquetadas</h2>

<p>Antes de explorar otros usos exóticos, aquí hay uno más tradicional —un Service Worker puede utilizar los recursos fuera de linea, <strong><a href="https://serviceworke.rs/cache-from-zip.html" target="_blank">mediante la instalación de aplicaciones empaquetadas</a></strong>. Es posible descargar un sencillo paquete comprimido y descomprimirlo en el momento de la activación por Service Worker. Esto reduce la sobrecarga introducida por cada una de las solicitudes HTTP y hace de la descarga de los recursos una operación atómica. El almacenamiento inteligente y automático de grandes cantidades de recursos como son fuentes o imágenes es otro buen ejemplo de funcionamiento fuera de linea.</p>

<h2>Imitar servidores</h2>

<p>Recordando la aproximación del intermediario, actuando como proxy un service worker podría <strong><a href="https://serviceworke.rs/virtual-server.html" target="_blank">imitar un servidor</a></strong> y ejecutar la API que el cliente espera alcanzar a traves de la red. <a href="https://github.com/gaia-components/serviceworkerware/" target="_blank">ServiceWorkerWare</a>, desarrollado dentro de Firefox OS, es una biblioteca para apoyar la  <a href="https://wiki.mozilla.org/Gaia/Architecture_Proposal" target="_blank">Nueva Arquitectura Gaia </a> para aplicaciones y permitir a los desarrolladores escribir Service Workers de <em>manera declarativa</em>, siguiendo la filosofía del popular Nodo.js <a href="http://expressjs.com/starter/hello-world.html" target="_blank">Express</a> pero con la biblioteca en el lado del cliente.</p>

<h2>Implementar funcionalidad en estructuras modernas</h2>

<p>Service Workers tambien tiene su propio lugar como constructor de bloques para modernas estructuras. Considerar la interpolación de plantillas como un ejemplo. Montones de estructuras de actuales aplicaciones web muy populares como <a href="http://backbonejs.org/" target="_blank">backbone.js</a> y <a href="https://angular.io/" target="_blank">Angular</a> reproducen modelos mediante su interpolación en una plantilla. La Nueva Arquitectura Gaia de la que hablamos previamente introduce el concepto de un <strong><a href="https://serviceworke.rs/render-store.html" target="_blank">almacen de reproducción</a></strong>, un caché fuera de linea almacenado como resultado de la interpolación de la plantilla con el modelo de datos de manera que la segunda vez que el cliente solicita el mismo modelo, este se puede recuperar desde el almacen de reproducción, evitando <a href="http://unoyunodiez.com/2015/09/07/modern-mobile-web-development-breaking-the-rules-beating-delays-improving-responsiveness-and-performance-ii/" target="_blank">retrasos de interpolación</a>.</p>

<h2>Inyectar dependencia</h2>

<p>Otro concepto popular en las modernas estructuras es <strong><a href="https://serviceworke.rs/dependency-injector.html" target="_blank">Inyectar dependencia</a></strong>, el cual declara que la dependencia del código no necesita saber como se han construido estas dependencias. Este solo conoce el esquema de la comunicación , y la implementación específica es proporcionada por una fábrica desconocida llamada inyector. Un Service Worker puede actuar como inyector de dependencia. Una estructura puede hacer que estos componentes declaren dependencias a la API, entonces Service Worker, actúa como el inyector, puede identificar solicitudes desconocidas de recursos y responderlas con los módulos concretos.</p>

<h2>Aplazar solicitudes</h2>

<p>Si el dispositivo no tiene conectividad pero la aplicación sigue aceptando las operaciones, la aplicación cliente y el servidor en la nube estarán eventualmente fuera de sincronización. Una interesante propiedad para una estructura podría ser <strong><a href="https://serviceworke.rs/request-deferrer.html" target="_blank">aplazar solicitudes</a></strong>. Por ejemplo, mientras se está desconectado Service Worker puede retener solicitudes a la API y realizarlas cuando la conexión vuelva. Mientras tanto,  Service Worker puede imitar al servidor respondiendo el genérico OK (<a href="https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#200" target="_blank"> código de estado 200</a>) o ACEPTADO (<a href="https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#202" target="_blank">código de estado 202</a>) respuestas a las a las operaciones del cliente. Una vez regrese la conectividad,  Service Worker puede sincronizar con la nube recreando la devolución de las solicitudes a la red desde una cola de solicitudes diferidas.</p>

**Comment by SoftwareRVG** [comment]
### jorge, ya he terminado la traducción del artículo. Lo paso a revisión.Debajo te dejo un enlace de google docks con el documento terminado. Tambien  envío el enlace a tu correo personal.

Aqui os dejo el documento terminado:

https://docs.google.com/document/d/1FxiXop9tHe6S94purxI8sF5n18yyZdCD9A6K0eM2Kgc/edit#heading=h.35qv1fkopcy

<div id="content-head" class="section">
  <h1 class="post__title">Mas allá,sin conexión</h1>
  <div class="byline">
    <h3 class="post__author">
                      <img alt='' src='https://secure.gravatar.com/avatar/51e4f6459f94a04520ee141daeed3af0?s=64&#038;d=mm&#038;r=g' srcset='https://secure.gravatar.com/avatar/51e4f6459f94a04520ee141daeed3af0?s=128&amp;d=mm&amp;r=g 2x' class='avatar avatar-64 photo' height='64' width='64' />        Por
                                        <a class="url" href="http://unoyunodiez.com" rel="external me">Salva</a>                            </h2>
    <div class="post__meta">
      Publicado el
      <abbr class="published" title="2015-12-21T12:23:56-08:00">
        21 Diciembre, 2015      </abbr>
      <span class="entry-cat">en
        <a href="https://hacks.mozilla.org/category/serviceworkers/" rel="category tag" title="View all posts in ServiceWorkers" >ServiceWorkers</a>      </span>
            <div class="socialshare" data-type="bubbles"></div>
    </div>
  </div>
</div>

<main id="content-main" class="section article"> 
  <article class="post" role="article">
    <p>Esta es mi primera publicación en Mozilla,y aparte de mi blog personal , esta es mi primera publicación como mozillian (yay!). Durante este mes he estado trabajando en el <a href="https://serviceworke.rs/" target="_blank">Service Worker Cookbook project</a> —parte de el <a href="https://wiki.mozilla.org/Apps" target="_blank">Web Application Developer Initiative</a> (WADI)— Que me ha dado la oportunidad de poner mi experiencia en ServicesWorkers a la práctica mientras que al mismo tiempo aprendía nuevas maneras de aprovechar esta excitante nueva tecnología web para el bien de la Web. Permitidme compartir con vosotros algunos de mis últimos pensamientos.</p>

<p>En la publicación previa de esta serie participó mi compañero <a href="http://davidwalsh.name/" target="_blank">David Walsh</a> hablando sobre <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache" target="_blank">Caché de Aplicación</a> y su falta de flexibilidad,por lo que no voy a profundizar mas en este tema. Sin embargo revisaré algo mas las recetas disponibles  en el Service Worker Cookbook.. David lo presentó y explicó algunas  <a href="https://hacks.mozilla.org/2015/11/offline-service-workers/" target="_blank">recetas fuera de linea</a>; Yo quiero ir un poco mas alla y ver algunos otros usos de Service Workers.</p>

<h2>Service workers hoy</h2>

<p>A pesar de haber estado en desarrollo durante algún tiempo,solo ahora comenzamos a escuchar que<a href="https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API" target="_blank"> Service Workers</a> está siendo utilizado líbremente. En resumen, esta API fué entregada originalmente para corregir lo que el caché de la aplicación hacía mal. <a href="https://github.com/slightlyoff/ServiceWorker/tree/63a184996d1fd199dea8e922b6edbd1fd4642748#whats-going-on-here" target="_blank">la arqueología web</a> revela que la intención fué precisamente fijar caché fuera de linea, permitiendo a los desarrolladores web<q>construir URL amigable,por defecto aplicaciones fuera de linea por capas de una manera fiable.</q>.</p>

<p>El planteamiento inicial introdujo el concepto de control de la navegación a través de un concepto que se desarrolló dentro de Service Worker’s <a href="https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent" target="_blank">recuperar la funcionalidad en el acto</a>: una manera de interceptar solicitudes de red y dar respuesta con los datos obtenidos, bases de datos o procedimiento generado. ¿La mejor parte? Las páginas controladas no tienen que saber que en realidad están siendo pirateadas (a pesar de que se les puede decir) por lo que la lógica  del servicio está complétamente disociada de la lógica de la aplicación. Un perfecto “intermediario”.</p>

<p>Pero como hackers (¡Este es el blog Hacks, después de todo!) Lo que nos gusta es elaborar soluciones ingeniosas a problemas relevantes en los que “ingeniosas” con frecuencia significa abusar de las intenciones reales de algo. En Mozilla, desde nuestras iniciativas WADI y Firefox OS estamos explorando los siguientes usos con etiqueta-desconectado de Service Workers.</p>

<h2>API analítica</h2>

<p>Vamos a comenzar con una aplicación directa del intermediario: <strong><a href="https://serviceworke.rs/api-analytics.html" target="_blank">API analytics</a></strong>. Imagina que deseas obtener estádistica de una API y no tienes acceso al servidor. Las soluciones actuales  manipulan la solicitud del cliente generando código HTTP , enviando los registros apropiados al servicio de analítica. Un Service Worker puede ir mas allá, interceptando cada solicitud, extrayendo los parámetros, y enviando el registro para analizar permitiendo que la solicitud original alcance la red.</p>

<h2>Instalar APPS empaquetadas</h2>

<p>Antes de explorar otros usos exóticos, aquí hay uno más tradicional —un Service Worker puede utilizar los recursos fuera de linea, <strong><a href="https://serviceworke.rs/cache-from-zip.html" target="_blank">mediante la instalación de aplicaciones empaquetadas</a></strong>. Es posible descargar un sencillo paquete comprimido y descomprimirlo en el momento de la activación por Service Worker. Esto reduce la sobrecarga introducida por cada una de las solicitudes HTTP y hace de la descarga de los recursos una operación atómica. El almacenamiento inteligente y automático de grandes cantidades de recursos como son fuentes o imágenes es otro buen ejemplo de funcionamiento fuera de linea.</p>

<h2>Imitar servidores</h2>

<p>Recordando la aproximación del intermediario, actuando como proxy un service worker podría <strong><a href="https://serviceworke.rs/virtual-server.html" target="_blank">imitar un servidor</a></strong> y ejecutar la API que el cliente espera alcanzar a traves de la red. <a href="https://github.com/gaia-components/serviceworkerware/" target="_blank">ServiceWorkerWare</a>, desarrollado dentro de Firefox OS, es una biblioteca para apoyar la  <a href="https://wiki.mozilla.org/Gaia/Architecture_Proposal" target="_blank">Nueva Arquitectura Gaia </a> para aplicaciones y permitir a los desarrolladores escribir Service Workers de <em>manera declarativa</em>, siguiendo la filosofía del popular Nodo.js <a href="http://expressjs.com/starter/hello-world.html" target="_blank">Express</a> pero con la biblioteca en el lado del cliente.</p>

<h2>Implementar funcionalidad en estructuras modernas</h2>

<p>Service Workers tambien tiene su propio lugar como constructor de bloques para modernas estructuras. Considerar la interpolación de plantillas como un ejemplo. Montones de estructuras de actuales aplicaciones web muy populares como <a href="http://backbonejs.org/" target="_blank">backbone.js</a> y <a href="https://angular.io/" target="_blank">Angular</a> reproducen modelos mediante su interpolación en una plantilla. La Nueva Arquitectura Gaia de la que hablamos previamente introduce el concepto de un <strong><a href="https://serviceworke.rs/render-store.html" target="_blank">almacen de reproducción</a></strong>, un caché fuera de linea almacenado como resultado de la interpolación de la plantilla con el modelo de datos de manera que la segunda vez que el cliente solicita el mismo modelo, este se puede recuperar desde el almacen de reproducción, evitando <a href="http://unoyunodiez.com/2015/09/07/modern-mobile-web-development-breaking-the-rules-beating-delays-improving-responsiveness-and-performance-ii/" target="_blank">retrasos de interpolación</a>.</p>

<h2>Inyectar dependencia</h2>

<p>Otro concepto popular en las modernas estructuras es <strong><a href="https://serviceworke.rs/dependency-injector.html" target="_blank">Inyectar dependencia</a></strong>, el cual declara que la dependencia del código no necesita saber como se han construido estas dependencias. Este solo conoce el esquema de la comunicación , y la implementación específica es proporcionada por una fábrica desconocida llamada inyector. Un Service Worker puede actuar como inyector de dependencia. Una estructura puede hacer que estos componentes declaren dependencias a la API, entonces Service Worker, actúa como el inyector, puede identificar solicitudes desconocidas de recursos y responderlas con los módulos concretos.</p>

<h2>Aplazar solicitudes</h2>

<p>Si el dispositivo no tiene conectividad pero la aplicación sigue aceptando las operaciones, la aplicación cliente y el servidor en la nube estarán eventualmente fuera de sincronización. Una interesante propiedad para una estructura podría ser <strong><a href="https://serviceworke.rs/request-deferrer.html" target="_blank">aplazar solicitudes</a></strong>. Por ejemplo, mientras se está desconectado Service Worker puede retener solicitudes a la API y realizarlas cuando la conexión vuelva. Mientras tanto,  Service Worker puede imitar al servidor respondiendo el genérico OK (<a href="https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#200" target="_blank"> código de estado 200</a>) o ACEPTADO (<a href="https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#202" target="_blank">código de estado 202</a>) respuestas a las a las operaciones del cliente. Una vez regrese la conectividad,  Service Worker puede sincronizar con la nube recreando la devolución de las solicitudes a la red desde una cola de solicitudes diferidas.</p>

<h2>Ideas lógicas en la red</h2>

<p>Y para finalizar, Service Worker también puede tener lógica en la red, quizás multiplexando una solicitud a multiples fuentes, midiendo la disponibilidad y calidad de cada fuente y devolviendo los datos por el canal correcto. Permitidme mostrar un pequeño ejemplo antes de finalizar. Suponer que tenemos una aplicación de video online. El usuario quiere ver una película  en HD entonces la aplicación solicita la URL de la película , pero antes de comenzar a servir el contenido Service Worker intercepta la solicitud, pregunta los niveles de descarga al servidor, selecciona uno con el valor mas bajo y comienza a servir el contenido desde ese servidor específico.¿ Suena familiar?.Es un <strong><a href="https://serviceworke.rs/load-balancer.html" target="_blank">Equilibrador de carga</a></strong>, si, pero ahora disponible en el lado del cliente!.Es bueno. ¿No es así?</p>

<h2>Resumen</h2>

<p>¡Eso es todo por ahora amigos!. Siete usos,siete recetas exóticas mas allá del simple almacenamiento de caché para su disponibilidad sin conexión. En este momento, <a href="https://serviceworke.rs/" target="_blank">Service Worker Cookbook project</a> expone todos estos modos (además de otros) para sacar provecho de las características proporcionadas por la API de  Service Workers . Y no nos detendremos aquí —hay mucho mas por explorar; <a href="https://developer.mozilla.org/en-US/docs/Web/API/Push_API" target="_blank">Push API</a> está aquí para permanecer. <a href="https://github.com/slightlyoff/BackgroundSync" target="_blank">Background Sync</a> llegará pronto, con respuestas streaming HTTP y solicitudes cancelables como horizonte. ¿Quién sabe que oportunidades tenemos por delante?</p>

<p>Para obtener mas información sobre Service Workers y cualquier otros estados de implementación de la plataforma, echa un vistazo a <a href="https://platatus.herokuapp.com/" target="_blank">Platatus</a>, y. ¡Te mantendremos informado!</p>    <section class="about">
                                <h2 class="about__header">Acerca de
                          <a class="url" href="http://unoyunodiez.com" rel="external me">
                Salva              </a>
                      </h3>
                      <p> Desarrollador de aplicaciones para usuario de Mozilla. Defensor de la Web-abierta, Me gusta programar,los idiomas , el cine, la música, los video-juegos y la cerveza.</p>

```
                <ul class="author-meta fa-ul"><li><i class="fa-li fa fa-globe"></i><a href="http://unoyunodiez.com" class="website" rel="me">unoyunodiez.com</a></li><li><i class="fa-li fa fa-twitter"></i><a href="http://twitter.com/salvadelapuente" class="twitter" rel="me">@salvadelapuente</a></li></ul>            <p><a class="url" href="https://hacks.mozilla.org/author/sdelapuentemozilla-com/">Mas artículos de Salva&hellip;</a></p>
              </section>
```

  </article>

<section class="discussion">
  <hr class="dino">
  <div class="comments">
    <header class="comments__head">
      <h3>2 comentarios</h3>
    </header>

```
      <ol class="comments__list" class="hfeed">
```

 <li id="comment-19291" class="comment even thread-even depth-1">
           <b class="comment__title">
       <a href="http://jamesjnadeau.com" class="url" rel="nofollow external" title="http://jamesjnadeau.com">
         <cite class="author fn">James Nadeau</cite>
       </a>
     </b>

```
<blockquote class="comment__body">
  <p>Estupendo artículo, nunca pensé en todas estas funciones, ¡Buen trabajo!</p>
</blockquote>

<a class="comment__meta" href="https://hacks.mozilla.org/2015/12/beyond-offline/#comment-19291" rel="bookmark" title="Permanent link to this comment by James Nadeau"><abbr class="published" title="2015-12-28">28 Diciembre, 2015</abbr> a las 12:02</a>
```

  </li>

 <li id="comment-19297" class="comment odd alt thread-odd thread-alt depth-1">
            <b class="comment__title vcard">
        <cite class="author fn">lv7777</cite>
      </b>

```
<blockquote class="comment__body">
  <p>Estaba traduciendo tu artículo.<br />
```

No sabía nada acerca de Service Worker hasta traducirlo,pero después me interesó Service Worker.</p>
    </blockquote>

```
<a class="comment__meta" href="https://hacks.mozilla.org/2015/12/beyond-offline/#comment-19297" rel="bookmark" title="Permanent link to this comment by lv7777"><abbr class="published" title="2016-01-07">7 Enero, 2016</abbr> a las 16:46</a>
```

  </li>
      </ol>
      </div>

<p class="comments__closed"><b>Los comentarios estan cerrados para este artículo.</b></p>

</main>

```
<footer class="footer section section--fullwidth">
  <div class="row">
    <p class="block block--1">
      Excepto donde se indique otra cosa, el contenido de este sitio
 se distribuye con licencia
      <a href="https://creativecommons.org/licenses/by-sa/3.0/" rel="license external">Creative Commons Attribution Share-Alike License v3.0</a>
      o una versión actualizada.
    </p>
    <img class="footer__logo" alt="the Mozilla dino logo" src="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/wp-content/themes/Hax/img/dino.svg">
  </div>
</footer>
```

  </div>
  <link rel='stylesheet' id='hljstheme-css'  href='https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/wp-content/plugins/wp-code-highlightjs/styles/default.css?ver=0.5.9' type='text/css' media='all' />

<script type='text/javascript' src='https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/wp-includes/js/wp-embed.min.js?ver=4.4.2'></script>

<script type='text/javascript' src='https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/wp-content/plugins/wp-code-highlightjs/highlight.common.pack.js?ver=0.5.9'></script>

<script type='text/javascript' src='https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/wp-content/plugins/wp-code-highlightjs/highlight.custom.pack.js?ver=0.5.9'></script>

```
<style>pre.hljs {padding: 5px;}
```

pre.hljs code {}</style>
    <script type="text/javascript">
    (function($, window) {
        var init_fn_flag = false;
        var init_fn = (function() {
            if (init_fn_flag)
                return;

```
        init_fn_flag = true;

         hljs.configure({"tabReplace":"    "});
        $('pre code').each(function(i, block) {
            hljs.highlightBlock(block);
        });

    });

    $(document).ready(init_fn);
    $(window).on("load", init_fn);
})(jQuery, window);
</script>
```

</body>
</html>

  </body>
</html>

**Comment by SoftwareRVG** [comment]
![Uploading HACKS_beyond_offline_by_Salva_translated_by_Rober_Villar.jpg…]()

**Comment by SoftwareRVG** [comment]
### Jorge. He terminado la traducción. Os dejo el enlace de edición de google docks:

https://docs.google.com/document/d/1FxiXop9tHe6S94purxI8sF5n18yyZdCD9A6K0eM2Kgc/edit#heading=h.35qv1fkopcy

Saludos:  Rober Villar

![hacks_beyond_offline_by_salva_translated_by_rober_villar](https://cloud.githubusercontent.com/assets/15747545/13712627/00f91f70-e7c5-11e5-88b7-69362287198c.jpg)

**Comment by jvillalobos** [comment]
@SoftwareRVG las tareas no se cierran hasta que el artículo esté publicado en el blog.

**Comment by SoftwareRVG** [comment]
De acuerdo . No me he dado cuenta  de que la dejaba cerrada. Ahora he visto el simbolo Jorge.No se como la he cerrado. El enlace de edición en Google Docks lo he dejado accesible para todos . Ya me daré cuenta para otra vez.Espero instrucciones

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/mas-alla-del-offline/

Gracias!
