### ISSUE TITLE
WebGL Off the Main Thread

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#54]
https://hacks.mozilla.org/2016/01/webgl-off-the-main-thread/

**Comment by Josexv1** [comment]
Realizare este.

**Comment by Josexv1** [comment]
Listo, aqui esta para revision. https://www.mozilla-hispano.org/?p=40057&preview=true

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/webgl-fuera-del-hilo-principal/

Gracias!
