### ISSUE TITLE
Google Analytics, Privacy, and Event Tracking

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#56]
https://hacks.mozilla.org/2016/01/google-analytics-privacy-and-event-tracking/

**Comment by cruzgerardo3** [comment]
me gustaria tomar este

**Comment by jvillalobos** [comment]
@cruzgerardo3 Ha habido algún progreso con esta traducción?

**Comment by parguello** [comment]
Me asigno este artículo, ya que veo que esta en estado pendiente.
Gracias! :)

**Comment by parguello** [comment]
El post se encuentra pendiente de revisión en WordPress.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/google-analytics-privacidad-y-rastreo-de-eventos/

Gracias!
