### ISSUE TITLE
HTML 5 game development video series

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#58]
https://hacks.mozilla.org/2016/02/html-5-game-development-video-series/

**Comment by xexio** [comment]
Hola, para traducirlo entiendo que también habría que poner subs a los videos, no?

**Comment by jvillalobos** [comment]
No es necesario. Para artículos anteriores simplemente hemos dejado los vídeos en inglés.

**Comment by xexio** [comment]
Pues me lo asigno y voy traduciendo

**Comment by xexio** [comment]
@jvillalobos  Os adjunto el documento con la traducción.
[html5_games_development.pdf](https://github.com/mozillahispano/blog-labs/files/143207/html5_games_development.pdf)

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/serie-de-videos-de-desarrollo-de-juegos-html5/

Gracias!
