### ISSUE TITLE
Implementing Content Security Policy

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#59]
https://hacks.mozilla.org/2016/02/implementing-content-security-policy/

**Comment by Josexv1** [comment]
Voy a realizar este, en un rato lo publico.

**Comment by Josexv1** [comment]
https://www.mozilla-hispano.org/?p=40089&preview=true
Esta lista la traduccion, realmente disfrute traducir este tema, ya que es un excelente tema!

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/implementando-politica-de-seguridad-csp/

Gracias!
