### ISSUE TITLE
Diving into Rust for the first time

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#6]
https://hacks.mozilla.org/2015/05/diving-into-rust-for-the-first-time/

**Comment by cruzgerardo3** [comment]
me gustaria

**Comment by jvillalobos** [comment]
Adelante. Le envié una invitación para unirse al grupo, y así le puedo asignar el artículo.

**Comment by cruzgerardo3** [comment]
https://docs.google.com/document/d/1qW7GEITpVTwZXmJpEeQQLPlEapd8ULvhiz0mm6yzO3c/edit?usp=sharing

**Comment by jvillalobos** [comment]
Publicado, gracias!
https://www.mozilla-hispano.org/aprendiendo-rust-por-primera-vez/
