### ISSUE TITLE
Introducing the WebVR 1.0 API Proposal

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#62]
https://hacks.mozilla.org/2016/03/introducing-the-webvr-1-0-api-proposal/

**Comment by Rixy8** [comment]
Hola, me gustaria trabajar en este articulo

**Comment by jvillalobos** [comment]
@Rixy8 adelante. Nos puede compartir la traducción usando Google Docs. Gracias!

**Comment by jvillalobos** [comment]
@Rixy8 Ha habido progreso con esta tarea?
