### ISSUE TITLE
Debugging Service Workers and Push with Firefox DevTools

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#64]
https://hacks.mozilla.org/2016/03/debugging-service-workers-and-push-with-firefox-devtools/

**Comment by parguello** [comment]
Hola! Me asigno este post para realizar la traducción.
Gracias,

**Comment by parguello** [comment]
Pendiente de revisión en WP

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/depurando-service-workers-y-push-con-las-herramientas-de-desarrollo-de-firefox/

Gracias!
