### ISSUE TITLE
A WebAssembly Milestone: Experimental Support in Multiple Browsers

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#65]
https://hacks.mozilla.org/2016/03/a-webassembly-milestone/

**Comment by xexio** [comment]
Me lo quedo para realizar la traducción

EDIT:  Al final por falta de tiempo no puedo realizarla, la vuelvo a dejar libre.

**Comment by jordicuevas** [comment]
Buenas tardes Jorge voy a realizar esta traducción. saludos!

**Comment by jordicuevas** [comment]
Buenas tardes anexo la traducción en un google doc. saludos! https://docs.google.com/document/d/1mU3c1QT3dGnMhFY6OLNaMzTYD2qglJ8kZBdzdaUfLwk/edit?usp=sharing

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/webassembly-soporte-en-varios-navegadores/

Gracias!
