### ISSUE TITLE
Developer Edition 47 – User agent emulation, popup debugging and more

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#66]
https://hacks.mozilla.org/2016/03/developer-edition-47-user-agent-emulation-popup-debugging-and-more/

**Comment by fdegiovanni** [comment]
Hola, quiero empezar a traducir este issue

**Comment by Josexv1** [comment]
Hola @fdegiovanni  puedes comenzar, @jvillalobos te enviara una solicitud de miembro para poder asignarte el issue. Cuando termines puedes entregarlo en un Google Docs.

**Comment by fdegiovanni** [comment]
Hola @Josexv1 Gracias!

**Comment by fdegiovanni** [comment]
@jvillalobos @Josexv1 Acá está mi documento con la traducción de la página. Los comentarios, ¿hay que traducirlos?
He resaltado en anaranjado aquellas partes en las que no sé como expresarlas correctamente en castellano...
[66 traduccion.docx](https://github.com/mozillahispano/blog-labs/files/201223/66.traduccion.docx)

**Comment by Josexv1** [comment]
Solo hace falta traducir el articulo.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/developer-edition-47-depuracion-agente-de-usuario-popups/

Gracias!
