### ISSUE TITLE
Referrer and cache control APIs for fetch()

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#67]
https://hacks.mozilla.org/2016/03/referrer-and-cache-control-apis-for-fetch/

**Comment by AngelFQC** [comment]
Pendiente de revisión

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/las-api-de-control-de-cache-y-de-referencia-para-fetch/

Gracias!
