### ISSUE TITLE
A-Frame 0.2.0 – The Extensible VR Web

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#69]
https://hacks.mozilla.org/2016/03/a-frame-0-2-0-the-extensible-vr-web/

**Comment by SoftwareRVG** [comment]
Jorge. ¿ Me puedes asignar este artículo ? . El anterior ya lo he pasado a revisión y te he dejado el enlace en GitHub y en tu correo personal.

Saludos a todos .  Rober Villar.

**Comment by jvillalobos** [comment]
Creo que se los puede asignar por cuenta propia, por cierto ;)

**Comment by SoftwareRVG** [comment]
<div id="content-head" class="section">
  <h1 class="post__title">A-Frame 0.2.0 &#8211; La Web de Realidad Virtual extensible</h1>
  <div class="byline">
    <h3 class="post__author">
                      <img alt='' src='https://secure.gravatar.com/avatar/9f001af90f9a126727df38e2097f1d64?s=64&#038;d=mm&#038;r=g' srcset='https://secure.gravatar.com/avatar/9f001af90f9a126727df38e2097f1d64?s=128&amp;d=mm&amp;r=g 2x' class='avatar avatar-64 photo' height='64' width='64' />        Por
                                        <a class="url" href="http://ngokevin.com" rel="external me">Kevin Ngo</a>                            </h2>
    <div class="post__meta">
      Publicado el
      <abbr class="published" title="2016-03-31T08:02:10-07:00">
         31 Marzo, 2016      </abbr>
      <span class="entry-cat">en
        <a href="https://hacks.mozilla.org/category/featured/" rel="category tag" title="View all posts in Featured Article" >Featured Article</a> y <a href="https://hacks.mozilla.org/category/webvr/" rel="category tag" title="View all posts in WebVR" >WebVR</a>      </span>
            <div class="socialshare" data-type="bubbles"></div>
    </div>
  </div>
</div>

<main id="content-main" class="section article">
  <article class="post" role="article">
    <p><a href="https://aframe.io">A-Frame</a> es un framework que hace mas fácil construir contenido de realidad virtual (VR) para la web. Este proporciona:</p>

<ul>
<li>La capacidad de construir escenas 3D con HTML declarativo.</li>
<li>Escenas adaptables WebVR a cualquier dispositivo que funcionan en plataformas múltiples.</li>
<li>Un <a href="https://wikipedia.org/wiki/Entity_component_system">patrón entidad-componente-sistema </a> que proporciona componibilidad y extensibilidad.</li>
</ul>

<p>Despues de tres divertidos meses ocupados con el desarrollo, estamos orgullosos de anunciar el lanzamiento de A-Frame version 0.2.0. El tema global de  esta versión es la <em>extensibilidad</em>. Para WebVR que evoluciona rápidamente, en un periodo en el que la realidad virtual (VR) esta dominada por ecosistemas nativos cerrados, A-Frame necesita permitir experimentación abierta y rápida interacción.La extensibilidad inherente de A-frame permite a los desarrolladores la innovación con menos permisos, haciendo de este sabor-VR la reencarnación del <a href="https://www.w3.org/community/nextweb/2013/06/11/the-extensible-web-manifesto/">Manifiesto Web Extensible</a>.</p>

<p>*Si no estas familiarizado, lee <a href="https://hacks.mozilla.org/2016/03/build-the-virtual-reality-web-with-a-frame/">Introducción previa del A-Frame en Mozilla Hacks</a>.</p>

<p><img src="https://cloud.githubusercontent.com/assets/674727/14156618/3258460c-f67c-11e5-8176-5b66c3169a1c.gif" alt="A-Frame Community Examples" /></p>

**Comment by SoftwareRVG** [comment]
<div id="content-head" class="section">
  <h1 class="post__title">A-Frame 0.2.0 &#8211; La Web de Realidad Virtual extensible</h1>
  <div class="byline">
    <h3 class="post__author">
                      <img alt='' src='https://secure.gravatar.com/avatar/9f001af90f9a126727df38e2097f1d64?s=64&#038;d=mm&#038;r=g' srcset='https://secure.gravatar.com/avatar/9f001af90f9a126727df38e2097f1d64?s=128&amp;d=mm&amp;r=g 2x' class='avatar avatar-64 photo' height='64' width='64' />        Por
                                        <a class="url" href="http://ngokevin.com" rel="external me">Kevin Ngo</a>                            </h2>
    <div class="post__meta">
      Publicado el
      <abbr class="published" title="2016-03-31T08:02:10-07:00">
         31 Marzo, 2016      </abbr>
      <span class="entry-cat">en
        <a href="https://hacks.mozilla.org/category/featured/" rel="category tag" title="View all posts in Featured Article" >Featured Article</a> y <a href="https://hacks.mozilla.org/category/webvr/" rel="category tag" title="View all posts in WebVR" >WebVR</a>      </span>
            <div class="socialshare" data-type="bubbles"></div>
    </div>
  </div>
</div>

<main id="content-main" class="section article">
  <article class="post" role="article">
    <p><a href="https://aframe.io">A-Frame</a> es un framework que hace mas fácil construir contenido de realidad virtual (VR) para la web. Este proporciona:</p>

<ul>
<li>La capacidad de construir escenas 3D con HTML declarativo.</li>
<li>Escenas adaptables WebVR a cualquier dispositivo que funcionan en plataformas múltiples.</li>
<li>Un <a href="https://wikipedia.org/wiki/Entity_component_system">patrón entidad-componente-sistema </a> que proporciona componibilidad y extensibilidad.</li>
</ul>

<p>Despues de tres divertidos meses ocupados con el desarrollo, estamos orgullosos de anunciar el lanzamiento de A-Frame version 0.2.0. El tema global de  esta versión es la <em>extensibilidad</em>. Para WebVR que evoluciona rápidamente, en un periodo en el que la realidad virtual (VR) esta dominada por ecosistemas nativos cerrados, A-Frame necesita permitir experimentación abierta y rápida interacción.La extensibilidad inherente de A-frame permite a los desarrolladores la innovación con menos permisos, haciendo de este sabor-VR la reencarnación del <a href="https://www.w3.org/community/nextweb/2013/06/11/the-extensible-web-manifesto/">Manifiesto Web Extensible</a>.</p>

<p>*Si no estas familiarizado, lee <a href="https://hacks.mozilla.org/2016/03/build-the-virtual-reality-web-with-a-frame/">Introducción previa del A-Frame en Mozilla Hacks</a>.</p>

<p><img src="https://cloud.githubusercontent.com/assets/674727/14156618/3258460c-f67c-11e5-8176-5b66c3169a1c.gif" alt="A-Frame Community Examples" /></p>

<h2>Desde el lanzamiento</h2>

<p>A-Frame ha recibido una respuesta muy positiva por la democratización en creación de contenido inmersivo 3D en la web. Los números:</p>

<ul>
<li>Más de 1500 estrellas, 25 colaboradores, 550 aportaciones en el <a href="https://github.com/aframevr/aframe"> repositorio A-Frame en GitHub </a>.</li>
<li>Más de 470 personas se han unido al <a href="https://aframevr-slack.herokuapp.com">A-Frame community Slack channel</a> para hacer preguntas, mostrar proyectos acabados, y simplemente para socializar.</li>
<li>Más de 100 impresionantes creaciones de gente inscrita en el <a href="https://github.com/aframevr/awesome-aframe">repositorio impresionante-aframe </a>.</li>
<li>Más de 50 proyectos exhibidos en <a href="http://aframevr.tumblr.com/">hecho con A-Frame Tumblr</a>.</li>
</ul>

<p>Miembros de la comunidad que han utilizado A-Frame para algunos usos interesantes:</p>

<ul>
<li><a href="http://kraeker.com">Donovan Kraeker</a> de <a href="http://drawvr.com">DrawVR</a> ha construido <a href="http://vr.ispystore.ca/">Varias tiendas VR </a> para realzar sus propiedades e-commerce esixtentes .</li>
<li><a href="http://drryanjames.github.io/">Ryan James</a>, un estudiante PhD  e investigador de la universidad de Washington, ha  <a href="https://www.youtube.com/watch?v=eYyuEjhD-k8">aplicado la realidad virtual a la educación médica</a>.</li>
<li><a href="https://twitter.com/donrmccurdy">Don McCurdy</a>, un ingeniero de software en Google, ha recreado una escena procedente del popular juego indie, <a href="https://sandbox.donmccurdy.com/vr/monument/">Valle del monumento</a>.</li>
</ul>

<p> A-Frame también ha recibido algún uso de un nivel más alto:</p>

<ul>
<li><a href="https://www.amnesty.org.uk/">Amnistía Internacional UK</a>, en colaboración con la empresa de diseño <a href="http://junior.io">Junior</a>, creó <a href="http://www.360syria.com/">360 Siria</a>, una experiencia que transporta a los espectadores a la sitiada ciudad de  Aleppo, Siria ,para presenciar la devastación de los "bombardeos barril" sobre sus ciudadanos.</li>
<li><a href="https://washingtonpost.com/">The Washington Post</a> publicó <em><a href="https://www.washingtonpost.com/graphics/business/mars-journey/">Marte: Un viaje interactivo</a></em> En el que se transporta a gente a la superficie del planeta rojo para aprender programas de exploración espacial.</li>

**Comment by SoftwareRVG** [comment]
<div id="content-head" class="section">
  <h1 class="post__title">A-Frame 0.2.0 &#8211; La Web de Realidad Virtual extensible</h1>
  <div class="byline">
    <h3 class="post__author">
                      <img alt='' src='https://secure.gravatar.com/avatar/9f001af90f9a126727df38e2097f1d64?s=64&#038;d=mm&#038;r=g' srcset='https://secure.gravatar.com/avatar/9f001af90f9a126727df38e2097f1d64?s=128&amp;d=mm&amp;r=g 2x' class='avatar avatar-64 photo' height='64' width='64' />        Por
                                        <a class="url" href="http://ngokevin.com" rel="external me">Kevin Ngo</a>                            </h2>
    <div class="post__meta">
      Publicado el
      <abbr class="published" title="2016-03-31T08:02:10-07:00">
         31 Marzo, 2016      </abbr>
      <span class="entry-cat">en
        <a href="https://hacks.mozilla.org/category/featured/" rel="category tag" title="View all posts in Featured Article" >Featured Article</a> y <a href="https://hacks.mozilla.org/category/webvr/" rel="category tag" title="View all posts in WebVR" >WebVR</a>      </span>
            <div class="socialshare" data-type="bubbles"></div>
    </div>
  </div>
</div>

<main id="content-main" class="section article">
  <article class="post" role="article">
    <p><a href="https://aframe.io">A-Frame</a> es un framework que hace mas fácil construir contenido de realidad virtual (VR) para la web. Este proporciona:</p>

<ul>
<li>La capacidad de construir escenas 3D con HTML declarativo.</li>
<li>Escenas adaptables WebVR a cualquier dispositivo que funcionan en plataformas múltiples.</li>
<li>Un <a href="https://wikipedia.org/wiki/Entity_component_system">patrón entidad-componente-sistema </a> que proporciona componibilidad y extensibilidad.</li>
</ul>

<p>Despues de tres divertidos meses ocupados con el desarrollo, estamos orgullosos de anunciar el lanzamiento de A-Frame version 0.2.0. El tema global de  esta versión es la <em>extensibilidad</em>. Para WebVR que evoluciona rápidamente, en un periodo en el que la realidad virtual (VR) esta dominada por ecosistemas nativos cerrados, A-Frame necesita permitir experimentación abierta y rápida interacción.La extensibilidad inherente de A-frame permite a los desarrolladores la innovación con menos permisos, haciendo de este sabor-VR la reencarnación del <a href="https://www.w3.org/community/nextweb/2013/06/11/the-extensible-web-manifesto/">Manifiesto Web Extensible</a>.</p>

<p>*Si no estas familiarizado, lee <a href="https://hacks.mozilla.org/2016/03/build-the-virtual-reality-web-with-a-frame/">Introducción previa del A-Frame en Mozilla Hacks</a>.</p>

<p><img src="https://cloud.githubusercontent.com/assets/674727/14156618/3258460c-f67c-11e5-8176-5b66c3169a1c.gif" alt="A-Frame Community Examples" /></p>

<h2>Desde el lanzamiento</h2>

<p>A-Frame ha recibido una respuesta muy positiva por la democratización en creación de contenido inmersivo 3D en la web. Los números:</p>

<ul>
<li>Más de 1500 estrellas, 25 colaboradores, 550 aportaciones en el <a href="https://github.com/aframevr/aframe"> repositorio A-Frame en GitHub </a>.</li>
<li>Más de 470 personas se han unido al <a href="https://aframevr-slack.herokuapp.com">A-Frame community Slack channel</a> para hacer preguntas, mostrar proyectos acabados, y simplemente para socializar.</li>
<li>Más de 100 impresionantes creaciones de gente inscrita en el <a href="https://github.com/aframevr/awesome-aframe">repositorio impresionante-aframe </a>.</li>
<li>Más de 50 proyectos exhibidos en <a href="http://aframevr.tumblr.com/">hecho con A-Frame Tumblr</a>.</li>
</ul>

<p>Miembros de la comunidad que han utilizado A-Frame para algunos usos interesantes:</p>

<ul>
<li><a href="http://kraeker.com">Donovan Kraeker</a> de <a href="http://drawvr.com">DrawVR</a> ha construido <a href="http://vr.ispystore.ca/">Varias tiendas VR </a> para realzar sus propiedades e-commerce esixtentes .</li>
<li><a href="http://drryanjames.github.io/">Ryan James</a>, un estudiante PhD  e investigador de la universidad de Washington, ha  <a href="https://www.youtube.com/watch?v=eYyuEjhD-k8">aplicado la realidad virtual a la educación médica</a>.</li>
<li><a href="https://twitter.com/donrmccurdy">Don McCurdy</a>, un ingeniero de software en Google, ha recreado una escena procedente del popular juego indie, <a href="https://sandbox.donmccurdy.com/vr/monument/">Valle del monumento</a>.</li>
</ul>

<p> A-Frame también ha recibido algún uso de un nivel más alto:</p>

<ul>
<li><a href="https://www.amnesty.org.uk/">Amnistía Internacional UK</a>, en colaboración con la empresa de diseño <a href="http://junior.io">Junior</a>, creó <a href="http://www.360syria.com/">360 Siria</a>, una experiencia que transporta a los espectadores a la sitiada ciudad de  Aleppo, Siria ,para presenciar la devastación de los "bombardeos barril" sobre sus ciudadanos.</li>
<li><a href="https://washingtonpost.com/">The Washington Post</a> publicó <em><a href="https://www.washingtonpost.com/graphics/business/mars-journey/">Marte: Un viaje interactivo</a></em> En el que se transporta a gente a la superficie del planeta rojo para aprender programas de exploración espacial.</li>
</ul>

<h2>Extensibilidad mejorada en A-Frame 0.2.0</h2>

<p>A-Frame trajo el patrón <em><a href="https://aframe.io/docs/core/">entidad-componente-sistema</a></em> a HTML. Todo en una<a href="https://aframe.io/docs/core/scene.html"> escena</a> es una <a href="https://aframe.io/docs/core/entity.html">entidad</a>. Una entidad es un contenedor general de objetos que inherentemente no hace ni reproduce nada. Los componentes son contenedores reutilizables más pequeños de datos y lógica ; cuando se conectan a las entidades, los componentes les proporcionan comportamiento, y funcionalidad. Los desarrolladores pueden escribir componentes para hacer lo que ellos quieren, con acceso directo a three.js, y despues compartirlos con la comunidad. Cualquier cosa que sea posible con three.js y WebGL es posible en in A-Frame.</p>

<p>Desde el lanzamiento inicial de A-frame, hemos estado refinando en gran medida el <a href="https://aframe.io/docs/core/component.html">componente API</a>. Lo realizamos a traves de ciclos de creación de componentes, descubriendo limitaciones en la API, y despues escribiendo patches para mejorar A-Frame. Mediante pruebas internas en nuestro propio framework, fuimos capaces de descubrir obstáculos en la extension de A-Frame:</p>

<ul>
<li>El componente API ha sido mejorado con los tipos de propiedad, configuración de esquema, y más métodos del ciclo de vida (<code>pausa</code>, <code>reproducción</code>, <code>tick</code>).</li>
<li>Primitivas (elementos de conveniencia como son <a href="https://aframe.io/docs/primitives/a-sphere.html"><code>&lt;a-sphera&gt;</code></a>) son capaces de tomar componentes.</li>
</ul>

<p>Ademas, hemos abierto más vías de escape a los desarrolladores para profundizar. Ahora pueden:</p> 

<ul>
<li>Definir tipos de propiedades personalizadas para componentes APIs más flexibles.</li>
<li>Registrar  lenguaje de sombreado (GLSL shaders) o material three.js .</li>
<li>Registrar primitivas.</li>
<li>Registrar sistemas que proporcienen ámbito global y servicios a los componentes.</li>
</ul>

<p>Lee las  <a href="https://github.com/aframevr/aframe/releases/tag/v0.2.0"> notas del lanzamiento de la versión completa 0.2.0 </a> para mas detalles.</p>

<h2>Encarnación de la web extensible VR </h2>

<p>La Extensible Web fomenta la competición saludable entre ideas y APIs. Solamente cuando emergen las ideas y las APIs están estabilizadas deberían ser estandarizadas. Es obligatorio seguir esta teoría para que la WebVR tenga éxito, de otra manera sería como si la Web llegara tarde a la fiesta cuando todas la patatas fritas ya se han comido. A-Frame es una encarnación de esas ideas.</p>

**Comment by SoftwareRVG** [comment]
<div id="content-head" class="section">
  <h1 class="post__title">A-Frame 0.2.0 &#8211; La Web de Realidad Virtual extensible</h1>
  <div class="byline">
    <h3 class="post__author">
                      <img alt='' src='https://secure.gravatar.com/avatar/9f001af90f9a126727df38e2097f1d64?s=64&#038;d=mm&#038;r=g' srcset='https://secure.gravatar.com/avatar/9f001af90f9a126727df38e2097f1d64?s=128&amp;d=mm&amp;r=g 2x' class='avatar avatar-64 photo' height='64' width='64' />        Por
                                        <a class="url" href="http://ngokevin.com" rel="external me">Kevin Ngo</a>                            </h2>
    <div class="post__meta">
      Publicado el
      <abbr class="published" title="2016-03-31T08:02:10-07:00">
         31 Marzo, 2016      </abbr>
      <span class="entry-cat">en
        <a href="https://hacks.mozilla.org/category/featured/" rel="category tag" title="View all posts in Featured Article" >Featured Article</a> y <a href="https://hacks.mozilla.org/category/webvr/" rel="category tag" title="View all posts in WebVR" >WebVR</a>      </span>
            <div class="socialshare" data-type="bubbles"></div>
    </div>
  </div>
</div>

<main id="content-main" class="section article">
  <article class="post" role="article">
    <p><a href="https://aframe.io">A-Frame</a> es un framework que hace mas fácil construir contenido de realidad virtual (VR) para la web. Este proporciona:</p>

<ul>
<li>La capacidad de construir escenas 3D con HTML declarativo.</li>
<li>Escenas adaptables WebVR a cualquier dispositivo que funcionan en plataformas múltiples.</li>
<li>Un <a href="https://wikipedia.org/wiki/Entity_component_system">patrón entidad-componente-sistema </a> que proporciona componibilidad y extensibilidad.</li>
</ul>

<p>Despues de tres divertidos meses ocupados con el desarrollo, estamos orgullosos de anunciar el lanzamiento de A-Frame version 0.2.0. El tema global de  esta versión es la <em>extensibilidad</em>. Para WebVR que evoluciona rápidamente, en un periodo en el que la realidad virtual (VR) esta dominada por ecosistemas nativos cerrados, A-Frame necesita permitir experimentación abierta y rápida interacción.La extensibilidad inherente de A-frame permite a los desarrolladores la innovación con menos permisos, haciendo de este sabor-VR la reencarnación del <a href="https://www.w3.org/community/nextweb/2013/06/11/the-extensible-web-manifesto/">Manifiesto Web Extensible</a>.</p>

<p>*Si no estas familiarizado, lee <a href="https://hacks.mozilla.org/2016/03/build-the-virtual-reality-web-with-a-frame/">Introducción previa del A-Frame en Mozilla Hacks</a>.</p>

<p><img src="https://cloud.githubusercontent.com/assets/674727/14156618/3258460c-f67c-11e5-8176-5b66c3169a1c.gif" alt="A-Frame Community Examples" /></p>

<h2>Desde el lanzamiento</h2>

<p>A-Frame ha recibido una respuesta muy positiva por la democratización en creación de contenido inmersivo 3D en la web. Los números:</p>

<ul>
<li>Más de 1500 estrellas, 25 colaboradores, 550 aportaciones en el <a href="https://github.com/aframevr/aframe"> repositorio A-Frame en GitHub </a>.</li>
<li>Más de 470 personas se han unido al <a href="https://aframevr-slack.herokuapp.com">A-Frame community Slack channel</a> para hacer preguntas, mostrar proyectos acabados, y simplemente para socializar.</li>
<li>Más de 100 impresionantes creaciones de gente inscrita en el <a href="https://github.com/aframevr/awesome-aframe">repositorio impresionante-aframe </a>.</li>
<li>Más de 50 proyectos exhibidos en <a href="http://aframevr.tumblr.com/">hecho con A-Frame Tumblr</a>.</li>
</ul>

<p>Miembros de la comunidad que han utilizado A-Frame para algunos usos interesantes:</p>

<ul>
<li><a href="http://kraeker.com">Donovan Kraeker</a> de <a href="http://drawvr.com">DrawVR</a> ha construido <a href="http://vr.ispystore.ca/">Varias tiendas VR </a> para realzar sus propiedades e-commerce esixtentes .</li>
<li><a href="http://drryanjames.github.io/">Ryan James</a>, un estudiante PhD  e investigador de la universidad de Washington, ha  <a href="https://www.youtube.com/watch?v=eYyuEjhD-k8">aplicado la realidad virtual a la educación médica</a>.</li>
<li><a href="https://twitter.com/donrmccurdy">Don McCurdy</a>, un ingeniero de software en Google, ha recreado una escena procedente del popular juego indie, <a href="https://sandbox.donmccurdy.com/vr/monument/">Valle del monumento</a>.</li>
</ul>

<p> A-Frame también ha recibido algún uso de un nivel más alto:</p>

<ul>
<li><a href="https://www.amnesty.org.uk/">Amnistía Internacional UK</a>, en colaboración con la empresa de diseño <a href="http://junior.io">Junior</a>, creó <a href="http://www.360syria.com/">360 Siria</a>, una experiencia que transporta a los espectadores a la sitiada ciudad de  Aleppo, Siria ,para presenciar la devastación de los "bombardeos barril" sobre sus ciudadanos.</li>
<li><a href="https://washingtonpost.com/">The Washington Post</a> publicó <em><a href="https://www.washingtonpost.com/graphics/business/mars-journey/">Marte: Un viaje interactivo</a></em> En el que se transporta a gente a la superficie del planeta rojo para aprender programas de exploración espacial.</li>
</ul>

<h2>Extensibilidad mejorada en A-Frame 0.2.0</h2>

<p>A-Frame trajo el patrón <em><a href="https://aframe.io/docs/core/">entidad-componente-sistema</a></em> a HTML. Todo en una<a href="https://aframe.io/docs/core/scene.html"> escena</a> es una <a href="https://aframe.io/docs/core/entity.html">entidad</a>. Una entidad es un contenedor general de objetos que inherentemente no hace ni reproduce nada. Los componentes son contenedores reutilizables más pequeños de datos y lógica ; cuando se conectan a las entidades, los componentes les proporcionan comportamiento, y funcionalidad. Los desarrolladores pueden escribir componentes para hacer lo que ellos quieren, con acceso directo a three.js, y despues compartirlos con la comunidad. Cualquier cosa que sea posible con three.js y WebGL es posible en in A-Frame.</p>

<p>Desde el lanzamiento inicial de A-frame, hemos estado refinando en gran medida el <a href="https://aframe.io/docs/core/component.html">componente API</a>. Lo realizamos a traves de ciclos de creación de componentes, descubriendo limitaciones en la API, y despues escribiendo patches para mejorar A-Frame. Mediante pruebas internas en nuestro propio framework, fuimos capaces de descubrir obstáculos en la extension de A-Frame:</p>

<ul>
<li>El componente API ha sido mejorado con los tipos de propiedad, configuración de esquema, y más métodos del ciclo de vida (<code>pausa</code>, <code>reproducción</code>, <code>tick</code>).</li>
<li>Primitivas (elementos de conveniencia como son <a href="https://aframe.io/docs/primitives/a-sphere.html"><code>&lt;a-sphera&gt;</code></a>) son capaces de tomar componentes.</li>
</ul>

<p>Además, hemos abierto más vías de escape a los desarrolladores para profundizar. Ahora pueden:</p> 

<ul>
<li>Definir tipos de propiedades personalizadas para componentes APIs más flexibles.</li>
<li>Registrar  lenguaje de sombreado (GLSL shaders) o material three.js .</li>
<li>Registrar primitivas.</li>
<li>Registrar sistemas que proporcionen ámbito global y servicios a los componentes.</li>
</ul>

<p>Lee las  <a href="https://github.com/aframevr/aframe/releases/tag/v0.2.0"> notas del lanzamiento de la versión completa 0.2.0 </a> para más detalles.</p>

<h2>Encarnación de la web extensible VR </h2>

<p>La Web Extensible fomenta la competición saludable entre ideas y APIs. Solamente cuando emergen las ideas y las APIs están estabilizadas deberían ser estandarizadas. Es obligatorio seguir esta teoría para que la WebVR tenga éxito, de otra manera sería como si la Web llegara tarde a la fiesta cuando todas la patatas fritas ya se han comido. A-Frame es una encarnación de esas ideas.</p>

<p>Como se ha mencionado antes, con A-Frame se construye sobre un patrón entidad-componente-sistema , los desarrolladores pueden escribir, compartir, y conectar componentes que añaden nuevas características . Si una característica todavía no esixte o no está a la altura, la comunidad puede mejorarla. El ecosistema ya cuenta con componentes integrados construidos por la comunidad que habilitan los controles gamepad , reconocimiento de voz, y físico. Con este sistema de innovación a corto plazo, los desarrolladores pueden experimentar rápidamente con ideas con objeto de ayudar en el avance no unicamente de  A-Frame sino también de WebVR.</p>

<p>Por ejemplo, <a href="https://twitter.com/donrmccurdy">Don McCurdy</a> interactúa sobre los componentes standard A-Frame  en su repositorio A-Frame playground , mientras que el equipo principal A-Frame ha trabajado sobre la activación de la extensibilidad. A partir de eso, ha rediseñado y mejorado todo el sistema físico de control en A-Frame. Con esos componentes probados, vamos mejorando la colección de componentes estándar en A-Frame.</p>

<p>Mucha gente en la comunidad estuvo buscando una manera de interpretar elementos de  texto y HTML como texturas en A-Frame. El estudiante <a href="https://twitter.com/a9_io">Max Krieger</a> escribió e intensificó componentes para permitir el uso del elemento<code>&lt;canvas&gt;</code> como una textura que permite ajustes de texto.</p>

<p>También, <a href="https://twitter.com/bnolan">Ben Nolan</a> de <a href="https://www.scenevr.com/">SceneVR</a> recientemente ha aportado su código del lado-cliente para utilizar A-Frame. Ha desarrollado componentes que permiten experiencias interactivas y multi-usuario, características que el equipo principal de A-Frame tenía como objetivo para finales de este año. Además, Ben está trabajando en un editor<a href="https://wikipedia.org/wiki/WYSIWYG">WYSIWYG</a> para escenas A-Frame . Nosotros también estamos trabajando en un editor.</p>

<p>Este virtuoso ciclo de la comunidad habilitando características y compartiendo componentes continua siendo un beneficio enorme para el ecosistema WebVR . En lugar de diseñar lentamente a puerta cerrada, construimos A-Frame para que toda la comunidad web ayudara en el esfuerzo. Juntos probaremos muchas cosas y lentamente nos centraremos en las que funcionan.</p>

<h2>Mirando hacia el futuro</h2>

<p>Trabajaremos en la construcción de mas demostraciones, mejorando interactividad, y las bajas de rendimiento. Una vez que el adaptador polyfill este estabilizado, daremos a conocer rapidamente el <a href="https://hacks.mozilla.org/2016/03/introducing-the-webvr-1-0-api-proposal/">soporte WebVR 1.0 </a> en A-Frame.</p>    <section class="about">
                                <h2 class="about__header">Acerca de 
                          <a class="url" href="http://ngokevin.com" rel="external me">
                Kevin Ngo              </a>
                      </h3>
                      <p>Kevin es un desarrollador de realidad virtual de Mozilla y desarrollador principal en A-Frame, un framework de código-abierto WebVR . El es @ngokevin_ en Twitter.</p>

```
                <ul class="author-meta fa-ul"><li><i class="fa-li fa fa-globe"></i><a href="http://ngokevin.com" class="website" rel="me">ngokevin.com</a></li><li><i class="fa-li fa fa-twitter"></i><a href="http://twitter.com/andgokevin" class="twitter" rel="me">@andgokevin</a></li></ul>            <p><a class="url" href="https://hacks.mozilla.org/author/kevinngo/">Más artículos de Kevin Ngo&hellip;</a></p>
              </section>
```

  </article>

<section class="discussion">
  <hr class="dino">
  <div class="comments">
    <header class="comments__head">
      <h3>2 commentarioss</h3>
    </header>

```
      <ol class="comments__list" class="hfeed">
```

 <li id="comment-19619" class="comment even thread-even depth-1">
            <b class="comment__title vcard">
        <cite class="author fn">Angel Celis Botto</cite>
      </b>

```
<blockquote class="comment__body">
  <p>Holy, muy interesante!!</p>
</blockquote>

<a class="comment__meta" href="https://hacks.mozilla.org/2016/03/a-frame-0-2-0-the-extensible-vr-web/#comment-19619" rel="bookmark" title="Permanent link to this comment by Angel Celis Botto"><abbr class="published" title="2016-03-31">31 Marzo, 2016</abbr> a las 16:34</a>

  <p class="comment__util"> </p>
```

  </li>

 <li id="comment-19846" class="comment odd alt thread-odd thread-alt depth-1">
           <b class="comment__title">
       <a href="http://www.iansun.com/" class="url" rel="nofollow external" title="http://www.iansun.com/">
         <cite class="author fn">Ian Sun.Ra</cite>
       </a>
     </b>

```
<blockquote class="comment__body">
  <p>Magnífico trabajo Kevin, soy un director de cine contando mis historias en un mundo de realidad virtual con 360 grados . Estoy intentando aprender tanto como pueda en el menor espacio posible de tiempo. A-Frame parece ser una increible y accesible herramienta,espero utilizarla para ayudar a contar nuevas historias.</p>
</blockquote>

<a class="comment__meta" href="https://hacks.mozilla.org/2016/03/a-frame-0-2-0-the-extensible-vr-web/#comment-19846" rel="bookmark" title="Permanent link to this comment by Ian Sun.Ra"><abbr class="published" title="2016-04-27">27 Abril, 2016</abbr> a las 23:01</a>

  <p class="comment__util"> </p>
```

  </li>
      </ol>
      </div>

<p class="comments__closed"><b>Los comentarios para este artículo están cerrados.</b></p>

</main>

```
<footer class="footer section section--fullwidth">
  <div class="row">
    <p class="block block--1">
      Excepto donde indique otra cosa, el contenido de este sitio se distribuye con licencia
      <a href="https://creativecommons.org/licenses/by-sa/3.0/" rel="license external">Creative Commons Attribution Share-Alike License v3.0</a>
      o cualquier versión actualizada.
    </p>
    <img class="footer__logo" alt="the Mozilla dino logo" src="https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/wp-content/themes/Hax/img/dino.svg">
  </div>
</footer>
```

  </div>
  <link rel='stylesheet' id='hljstheme-css'  href='https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/wp-content/plugins/wp-code-highlightjs/styles/default.css?ver=0.5.9' type='text/css' media='all' />

<script type='text/javascript' src='https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/wp-includes/js/wp-embed.min.js?ver=4.4.2'></script>

<script type='text/javascript' src='https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/wp-content/plugins/wp-code-highlightjs/highlight.common.pack.js?ver=0.5.9'></script>

<script type='text/javascript' src='https://2r4s9p1yi1fa2jd7j43zph8r-wpengine.netdna-ssl.com/wp-content/plugins/wp-code-highlightjs/highlight.custom.pack.js?ver=0.5.9'></script>

```
<style>pre.hljs {padding: 5px;}
```

pre.hljs code {}</style>
    <script type="text/javascript">
    (function($, window) {
        var init_fn_flag = false;
        var init_fn = (function() {
            if (init_fn_flag)
                return;

```
        init_fn_flag = true;

         hljs.configure({"tabReplace":"    "});
        $('pre code').each(function(i, block) {
            hljs.highlightBlock(block);
        });

    });

    $(document).ready(init_fn);
    $(window).on("load", init_fn);
})(jQuery, window);
</script>
```

  <script>
    // External links should open in a new tab.
    (function () {
      var postLinks = document.querySelectorAll('#content-main a');

```
  var origin = location.origin;

  for (var i = 0; i < postLinks.length; i++) {
    var link = postLinks[i];
    if (link.origin !== origin && !link.getAttribute('target')) {
      link.setAttribute('target', '_blank');
    }
  }
})();
```

  </script>
</body>
</html>

**Comment by SoftwareRVG** [comment]
Jorge. Aqui os dejo el enlace de Google-docs para la edición. 

Ahora miro por ahi a ver que árticulos tienes y  solicito que me asignes alguno. 
Saludos a todos , comunidad.

##  Rober Villar. ([ @SoftwareRVG](https://github.com/SoftwareRVG) )

### Enlace artículo original:  [https://hacks.mozilla.org/2016/03/a-frame-0-2-0-the-extensible-vr-web/](https://hacks.mozilla.org/2016/03/a-frame-0-2-0-the-extensible-vr-web/)

### Enlace artículo traducido: https://docs.google.com/document/d/1EZJkHySbqmjKA94RX3GSSMWoFsXfEKEyvJ7Aehd7jzY/edit?usp=sharing

---

![fireshot screen capture 066 - a-frame 0_2_0 the extensible vr web mozilla hacks the web developer blog - _c__users_robervillargarcia_desktop](https://cloud.githubusercontent.com/assets/15747545/15270706/2ba13384-1a29-11e6-840e-a1c2bf0424f2.png)

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/a-frame-0-2-0-realidad-virtual-extensible/

Gracias!
