### ISSUE TITLE
New Performance Tools in Firefox Developer Edition 40

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#7]
https://hacks.mozilla.org/2015/06/new-performance-tools-in-firefox-developer-edition-40/

**Comment by Skatox** [comment]
Puedo encargarme de traducir esta.

**Comment by jvillalobos** [comment]
Bien, veo que esto funciona ;)

**Comment by Skatox** [comment]
Actualicé el texto, pero no pude subir las imágenes, mi cuenta parece no tener permiso para poder subir las imágenes ni a imagen destacada. ¿Puedes arreglar eso?

**Comment by jvillalobos** [comment]
No, creo que no puedo cambiar permisos, así que mejor le pregunta a Guillermo. Si no se los arreglan antes de la revisión, yo pongo las imágenes.

**Comment by Skatox** [comment]
Listo, actualmente puedes chequearlo en https://www.mozilla-hispano.org/?p=39132&preview=true ya las imágenes se subieron al blog de MH Labs

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/nuevas-herramientas-de-rendimiento-en-firefox-40/

Gracias!
