### ISSUE TITLE
Optimizing JavaScript Performance With Firefox Dev Tools

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#70]
https://hacks.mozilla.org/2016/04/optimizing-javascript-performance-with-firefox-dev-tools/

**Comment by Skatox** [comment]
Este artículo es corto y el vídeo está en ingles. Me llamaría la atención traducirlo pero no sé si deberia hacerlo por el vídeo, ¿o se coloca en inglés y ya?

**Comment by jordicuevas** [comment]
Hola Miguel, el video lo podemos traducir por Amara y colocarle los subtitulos!.

**Comment by jvillalobos** [comment]
Si se pueden agregar subtítulos está genial, pero en general los estamos dejando en inglés.

**Comment by xexio** [comment]
Me la quedo para la traducción.

**Comment by xexio** [comment]
Lista, siento el retraso

[herramientas_rendimiento_js.pdf](https://github.com/mozillahispano/blog-labs/files/343863/herramientas_rendimiento_js.pdf)

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/optimizando-el-rendimiento-de-javascript-con-firefox/

Gracias!
