### ISSUE TITLE
How to implement SRI in your build process

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#72]
https://hacks.mozilla.org/2016/04/how-to-implement-sri-into-your-build-process/

**Comment by Josexv1** [comment]
Voy a tomar este.

**Comment by Josexv1** [comment]
Sorry por lo tarde.
https://www.mozilla-hispano.org/?p=40380&preview=true

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/implementar-sri-en-proceso-de-build/

Gracias!
