### ISSUE TITLE
You might not need a CSS framework

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#73]
https://hacks.mozilla.org/2016/04/you-might-not-need-a-css-framework/

**Comment by jordicuevas** [comment]
Buenas noches Jorge , anexo Google Doc con la traducción . saludos! https://docs.google.com/document/d/1PKwNnA4K2yOhiFD--fEOGDQoQaE1aqLWjFKGKzKbKlA/edit?usp=sharing

**Comment by Josexv1** [comment]
Hola @jordicuevas debes esperar a que @jvillalobos publique el tema para que se pueda cerrar el Issue.

**Comment by jordicuevas** [comment]
Hola @Josexv1 , gracias por la acotación , no se pq pense que ya Jorge lo habia revisado. Gracias! .

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/puede-que-no-necesites-un-framework-css/

Gracias!
