### ISSUE TITLE
Developer Edition 48 – Firebug features, editable storage, inspector improvements and more…

### ISSUE THREAD

**Issue by Skatox** [mozillahispano/blog-labs#75]
https://hacks.mozilla.org/2016/05/developer-edition-48-firebug-features-editable-storage-inspector-improvements-and-more/

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/developer-edition-48-firebug-almacenamiento-inspector-y-mas/

Gracias!
