### ISSUE TITLE
Using Google u in Extensions

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#76]
https://blog.mozilla.org/addons/2016/05/31/using-google-analytics-in-extensions/

**Comment by jordicuevas** [comment]
Buenas noches , anexo enlace con la traducción. https://docs.google.com/document/d/1HSXJidK6Jq8hcaz67gOh5LsBwCioIcqNS31K6VT5fyo/edit?usp=sharing 

Saludos!

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/usando-google-analytics-en-extensiones/

Gracias!
