### ISSUE TITLE
CSS coding techniques

### ISSUE THREAD

**Issue by jordicuevas** [mozillahispano/blog-labs#77]
https://hacks.mozilla.org/2016/05/css-coding-techniques/

**Comment by josenriq** [comment]
Puedo encargarme de este. Pero no estoy seguro si está disponible. Me avisan.

**Comment by jvillalobos** [comment]
Listo, asignado.

**Comment by jvillalobos** [comment]
@linktothapast Cuál es el estado de esta tarea?

**Comment by josenriq** [comment]
@jvillalobos Justo comencé hoy. Llevo como un 25% en una hora.

**Comment by josenriq** [comment]
Ya llevo como 70%. Este fin de semana lo termino. Pero tengo unas preguntas, por ser mi primera vez:
- ¿Cómo manejan los snippets de código en Google Docs?
- ¿Normalmente los traducen en tu, vos o usted?
- Cuando hay links a otros artículos, ¿cómo los reemplazan? Pregunto porque son links hacia artículos en inglés y en otro dominio...

**Comment by josenriq** [comment]
Listo. Dejé un comentarios (pregunta), específicamente sobre click vs clic

https://docs.google.com/document/d/1p6YY6iHKQdumOEcdwP6MwU0Di2nMqQrAmSdu8HdiL2c/edit?usp=sharing

**Comment by josenriq** [comment]
@jvillalobos Le dejé este hace más de un mes. No sé si es que no lo vio, o si hice algo mal y no se dio cuenta? Jeje. Fyi

**Comment by jvillalobos** [comment]
Hay una cola de traducciones que voy procesando en orden. Y también estaba de vacas, así que llevo como dos semanas de no hacer nada :P

**Comment by josenriq** [comment]
Ah ok, todo bien. Nada más cerciorándome.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/tecnicas-de-desarrollo-con-css/

Gracias!
