### ISSUE TITLE
Helping web developers with JavaScript errors

### ISSUE THREAD

**Issue by AngelFQC** [mozillahispano/blog-labs#79]
https://hacks.mozilla.org/2016/06/helping-web-developers-with-javascript-errors/

**Comment by AngelFQC** [comment]
Esta ya se puede publicar @jvillalobos

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/ayudando-a-desarrolladores-con-errores-de-javascript/

Gracias!
