### ISSUE TITLE
ES6 In Depth: Arrow functions

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#8]
https://hacks.mozilla.org/2015/06/es6-in-depth-arrow-functions/

**Comment by Josexv1** [comment]
Comenzare a traducir la serie de ES6. Comienzo con esta.

**Comment by Josexv1** [comment]
Aquí esta la traducción lista: https://www.dropbox.com/s/omofrda6tef5km8/ES6%20funciones%20de%20flechas.odt?dl=0 Esta corregida al español.

**Comment by jvillalobos** [comment]
Hola Jose. Me pareció ver que tiene acceso al Wordpress de Mozilla Hispano, así que sería mejor para mí que deje el artículo como un borrador pendiente de revisión. Gracias!

**Comment by Josexv1** [comment]
Hola @jvillalobos Si tengo acceso. Ya he colocado el borrador, para que lo revises por ahi. Que dificil es editar todo desde alli. Lo que no pude hacer fue la cita de codigo. asi que encerre todo en < code>< pre>. Aqui esta el [link](https://www.mozilla-hispano.org/?p=39208&preview=true)

**Comment by jvillalobos** [comment]
Publicado. ¡Gracias!
https://www.mozilla-hispano.org/es6-en-detalle-funciones-flecha/
