### ISSUE TITLE
WebExtensions for Firefox 49

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#81]
https://blog.mozilla.org/addons/2016/06/09/webextensions-for-firefox-49/

**Comment by parguello** [comment]
Hola Jorge! Me asigno esta tarea. 
Gracias.
Un saludo. :)

**Comment by parguello** [comment]
El artículo está pendiente de revisión en WordPress.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/webextensions-para-firefox-49/

Gracias!
