### ISSUE TITLE
Make the Web Work For Everyone

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#83]
https://hacks.mozilla.org/2016/07/make-the-web-work-for-everyone/

**Comment by siclemx** [comment]
Hola yo realizare esta traducción

Saludos
Uriel

**Comment by siclemx** [comment]
Listo https://docs.google.com/document/d/1v5EHogGA9fyjQ5IWSs_uh-t0KbVIWe5Df8bh2rlU0y4/edit?usp=sharing 

Saludos
Uriel

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/haz-que-la-web-trabaje-para-todos/

Gracias!
