### ISSUE TITLE
Learning to code for the Web: The MDN Learning Area welcomes you!

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#84]
https://hacks.mozilla.org/2016/06/learning-to-code-for-the-web-the-mdn-learning-area-welcomes-you/

**Comment by carloschocobar** [comment]
Hola Jorge, quiero traducir este artículo. Gracias.

Sent from Outlookhttp://aka.ms/weboutlook

**Comment by jvillalobos** [comment]
@carloschocobar Este artículo ya tiene un traductor asignado. Por el momento están libres el #56 y el #74.

**Comment by carloschocobar** [comment]
Perdón, no me fijé bien, entonces el #74.

Sent from Outlookhttp://aka.ms/weboutlook

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/aprende-a-programar-para-la-web-el-area-de-aprendizaje-de-mdn/

Gracias!
