### ISSUE TITLE
Reducing Adobe Flash Usage in Firefox

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#86]
https://blog.mozilla.org/futurereleases/2016/07/20/reducing-adobe-flash-usage-in-firefox/

**Comment by siclemx** [comment]
Jorge tomaré este articulo.

**Comment by jvillalobos** [comment]
Cómo va el progreso de esta traducción?

**Comment by siclemx** [comment]
Hola, voy un poco lento por algo de carga de trabajo, espero poder dedicarle más tiempo este fin de semana y tenerlo listo para el lunes o martes próximo.

**Comment by jvillalobos** [comment]
Genial, gracias :)

**Comment by siclemx** [comment]
Listo. https://docs.google.com/document/d/14YfSxER3kT3EgvGOYSSQC9CKIY009FG3FmJvWomoBAA/edit?usp=sharing  favor de verificar algunos tecnicismos que dejé tal cuál y no estoy 100% seguro de que tengan traducción.

Saludos!

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/reduciendo-el-uso-de-adobe-flash-en-firefox/

Gracias!
