### ISSUE TITLE
New WebExtensions Guides and How-tos on MDN

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#88]
https://blog.mozilla.org/addons/2016/07/21/new-webextensions-guides-and-how-tos-on-mdn/

**Comment by MoysesCM** [comment]
Hola me podrias asignar este artículo por favor

**Comment by jvillalobos** [comment]
Listo.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/nuevas-guias-y-tutoriales-webextensions/

Algunas notas: favor mantener los vínculos, mantener el tú (en vez de usted), y dejar los nombres como WebExtensions sin traducir.

¡Gracias!
