### ISSUE TITLE
Extension Signing: Availability of Unbranded Builds

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#89]
https://blog.mozilla.org/addons/2016/07/29/extension-signing-availability-of-unbranded-builds/

**Comment by SoftwareRVG** [comment]
Jorge, ¿ Me asignas este ?

**Comment by SoftwareRVG** [comment]
### Aqui os dejo el enlace de google docs con la traducción del artículo. y el articulo traducido. ¡ Saludos a todos !

### enlace: [https://docs.google.com/document/d/190bvFHrdTeQNao3hfGd4F-zeE_fejRxBqcO_mnaAEo0/edit?usp=sharing]

---

Mozilla Add-ons Blog
Mozilla
Extensión de firma: Disponibilidad de versiones sin marca
Kev Needham

64 comentarios

July
29
2016

Con el lanzamiento de Firefox 48,la extensión de firma ya no puede ser deshabilitada en el lanzamiento ,y el canal de versiones beta utiliza una preferencia. Como se señaló cuando la extensión de firma fué anunciada, estamos publicando versiones especializadas que soportan esta preferencia para que los desarrolladores puedan continuar probando el código que se genera en las versiones de lanzamiento y beta. Esas versiones no utilizan la marca Firefox , no se actualizan automaticamente, y solo estan disponibles para la configuración local en_US.

Puedes encontrar enlaces de las últimas versiones beta y lanzamientos en Extension Signing page a medida que van saliendo. la información adicional en Extension Signing, incluye una sección de preguntas frecuentes, que también está disponible en esta página.

---

![fireshot screen capture 220 - extension signing_ availability of unbranded builds i mozilla add-ons blog - _c__users_robervillargarcia_desktop_mozi](https://cloud.githubusercontent.com/assets/15747545/18252032/0787e106-738d-11e6-8b93-73b57b41768a.png)

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/firma-de-extensiones-versiones-de-prueba/

Gracias.
