### ISSUE TITLE
The state of Web Components

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#9]
https://hacks.mozilla.org/2015/06/the-state-of-web-components/

**Comment by fjaguero** [comment]
Me gustaría tomar este si está libre.

**Comment by jvillalobos** [comment]
Hola fjaguero, ha habido progreso con esta tarea?

**Comment by fjaguero** [comment]
Sí, tengo que terminarlo en breve y lo paso. ¿Tiene sentido añadir este al final como update? https://hacks.mozilla.org/2015/11/an-update-on-web-components-and-firefox/

**Comment by jvillalobos** [comment]
Creo que sí, aunque tal vez sería mejor combinar los artículos, de ser posible, si es que el segundo cambia cosas del primero.

**Comment by fjaguero** [comment]
En el último artículo sólo se menciona: lo que actualmente está shipped en Firefox (<template>), y se indica que Shadow DOM saldría para mitad de 2016, además de que los imports de HTML no serán lanzados de momento. Se puede añadir eso y dejar el mismo recap al final.

**Comment by jvillalobos** [comment]
Cuál es el estado de esta tarea?

**Comment by fjaguero** [comment]
Al final no lo terminé de traducir y unificar con el anterior. No sé si sigue valiendo la pena publicarlo por lo _outdated_ que está para hoy en día.

**Comment by jvillalobos** [comment]
Sí, supongo que ya está bastante viejo. Voy a cerrar la tarea.
