### ISSUE TITLE
https://hacks.mozilla.org/2016/08/developer-edition-50-console-memory-tool-net-monitor-and-more/

### ISSUE THREAD

**Issue by Skatox** [mozillahispano/blog-labs#90]
https://hacks.mozilla.org/2016/08/developer-edition-50-console-memory-tool-net-monitor-and-more/

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/edicion-desarrolladores-50-consola-herramienta-memoria-monitor-red/

Gracias!
