### ISSUE TITLE
What’s new in Web Audio?

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#92]
https://hacks.mozilla.org/2016/08/whats-new-in-web-audio-2/

**Comment by omarseguvi** [comment]
Quisiera traducir este. Gracias

**Comment by omarseguvi** [comment]
Listo aquí está la traducción
https://docs.google.com/document/d/1ReHYH0G5STF43h-1IJqPkTJt8XQRKcvXJyO9cuRYmKg/edit?usp=sharing

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/que-hay-de-nuevo-en-web-audio/

Gracias!
