### ISSUE TITLE
A few HTML tips

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#94]
https://hacks.mozilla.org/2016/08/a-few-html-tips/

**Comment by parguello** [comment]
Hola! Me asigno este post para traducir.
Un saludo.

**Comment by parguello** [comment]
Jorge, el artículo esta listo para revisión en WP.
En la parte final hay un link a codepen, que en el post original esta embebido dentro del artículo. Creo que para que se viera igual sería necesario el plugin codepen para wordpress
https://wordpress.org/plugins/codepen-embedded-pen-shortcode/
Ya me diras si crees que es necesario instalar este plugin para despues incluir el wordpress shortcode.

Un saludo.

**Comment by jvillalobos** [comment]
Gracias. Creo que he publicado artículos anteriormente con código así, y basta con copiar el código del iframe del artículo original.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/algunos-consejos-sobre-html/

Gracias!
