### ISSUE TITLE
debugger.html

### ISSUE THREAD

**Issue by Skatox** [mozillahispano/blog-labs#95]

**Comment by Skatox** [comment]
https://hacks.mozilla.org/2016/09/introducing-debugger-html/

**Comment by jvillalobos** [comment]
@Skatox Como va la traducción de este artículo?

**Comment by Skatox** [comment]
ups! lo habia olvidado. Esta semana lo haré!

**Comment by Skatox** [comment]
En revisión, me disculpo por el gran retraso

**Comment by jvillalobos** [comment]
Publicado. https://www.mozilla-hispano.org/presentando-debugger-html/

Gracias!
