### ISSUE TITLE
Firefox 49 fixes sites designed with WebKit in mind, and more

### ISSUE THREAD

**Issue by jordicuevas** [mozillahispano/blog-labs#96]
https://hacks.mozilla.org/2016/09/firefox-49-fixes-sites-designed-with-webkit-in-mind-and-more/

**Comment by jordicuevas** [comment]
buenas noches anexo google doc para su revisión https://docs.google.com/document/d/1VW8Q7Of3fVEfHkU_dws5HoTzaF4J6P0lO_wWeLUgmko/edit?usp=sharing. saludos

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/firefox-49-arregla-sitios-disenados-webkit-y-mas/

¡Gracias!
