### ISSUE TITLE
WebExtensions and parity with Chrome

### ISSUE THREAD

**Issue by jvillalobos** [mozillahispano/blog-labs#98]
https://blog.mozilla.org/addons/2016/09/13/webextensions-and-parity-with-chrome/

**Comment by parguello** [comment]
Me asigno este artículo para traducir. 
Saludos.

**Comment by parguello** [comment]
Preparado para revisión en Wordpress.

**Comment by jvillalobos** [comment]
Publicado: https://www.mozilla-hispano.org/webextensions-y-paridad-con-chrome/

Gracias!
